### ISSUE TITLE
Already looted (1536044792/-1118177488)

### ISSUE THREAD

**Issue by calienta** [Blackhandpl/bugtracker#1009]
1. Xelganak's Stinger
Bergruu's Horn
Aogexon's Fang
Dekorhan's Tusk
2. 118661
118655
118654
118656
3. nie można ponieść itemów Already looted (1536044792/-1118177488)
4. http://www.wowhead.com/item=118661/xelganaks-stinger
http://www.wowhead.com/item=118655/bergruus-horn
http://www.wowhead.com/item=118654/aogexons-fang
http://www.wowhead.com/item=118656/dekorhans-tusk

**Comment by ravel1** [comment]
#983

**Comment by Mendalista** [comment]
#983

**Comment by Mendalista** [comment]
#1012
