### ISSUE TITLE
Dream of a better tommorow

### ISSUE THREAD

**Issue by Ziombel** [Blackhandpl/bugtracker#1019]
Description: quest polega na zebraniu kilku elementów
Current behaviour: po otwarciu danych obiektów nic z nich nie wypada a zaraz po tym znikają
Expected behaviour: po otwarciu obiektu powinien się w nim znajdować quest item

Wowhead link: http://www.wowhead.com/quest=26026/dream-of-a-better-tomorrow

**Comment by grzewal1** [comment]
działa
