### ISSUE TITLE
Put the fear in them

### ISSUE THREAD

**Issue by Ziombel** [Blackhandpl/bugtracker#1029]
Description: Trzeba zabić 8 zwykłych żołnierzy i jednego "Honor's stand officer" 
Current behaviour: o ile zwykłych zalicza, tak tego drugiego nie da się zaznaczyć i wyskakuje komunikat "PVP nie jest włączone"

Wowhead link: http://www.wowhead.com/quest=24517/put-the-fear-in-them

**Comment by Gieniek** [comment]
Tak bo klikasz prawym na swojim zdjeciu w lewym gornym roku i zaznaczasz PvP  ON.
