### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by calienta** [Blackhandpl/bugtracker#1040]
1. skałki
2. ...
3. brak lootu ze skałek
4.http://www.wowhead.com/object=189980/saronite-deposit
http://www.wowhead.com/object=189978/cobalt-deposit
http://www.wowhead.com/object=189979/rich-cobalt-deposit

**Comment by thomas33** [comment]
#1041

**Comment by calienta** [comment]
nie rośnie skill, mimo kopania skałek które powinny dawać wzrost skill'a
