### ISSUE TITLE
Śmierć DC'kująca serwer

### ISSUE THREAD

**Issue by LoLfsztorm** [Blackhandpl/bugtracker#1042]
Parę razy spotkałem się z takim zjawiskiem że moja śmierć w Talador zamiast powodować pojawienie się okienka z opcją "uwolnienia ducha" to DC'kuje serwer . Raz doprowadziło to do patowej sytuacji w której umarłem w grupce mobów a po DC byłem żywy z ok 20% HP w tej grupce mobów co powodowało wielokrotnie moją śmierć a przy tym DC . Na szczęście uciekłem żywy od tych mobów a podczas tego incydentu chyba nikogo nie było na serwerze. Nie wiem czy ten błąd istnieje na innych krainach , o ile może to mieć cokolwiek z tym wspólnego.

**Comment by ravel1** [comment]
Gdzie dokładnie miało to miesjce? Możesz wrzucić SS'a z Twoja lokalizacją?

**Comment by ravel1** [comment]
Dzieje się to tylko w Draenorze? Za każdym razem czy jakoś losowo?
