### ISSUE TITLE
Spell  [Lonely Winter]

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#1045]
1. Spell  [Lonely Winter]
2. 205024
3. Nie można summon swojego peta. 
4. http://www.wowhead.com/spell=205024/lonely-winter

**Comment by ravel1** [comment]
**You can no longer summon your Water Elemental,** but Frostbolt, Ice Lance, Flurry, and Frozen Orb deal 25% increased damage.
