### ISSUE TITLE
Pet - Water Elemental Minor Talent Version

### ISSUE THREAD

**Issue by Icelandman** [Blackhandpl/bugtracker#106]
1. Pet - Water Elemental Minor Talent Version
2. 1777
3. skil miniona Waterbolt link: http://www.wowhead.com/spell=31707/waterbolt powinien zadawac % dmg od spell power
4. http://www.wowhead.com/skill=1777/pet-water-elemental-minor-talent-version

**Comment by ravel1** [comment]
Spell power has been removed in Legion.
