### ISSUE TITLE
NPC: Anya Maulray <Stable Master>

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#1061]
1. Anya Maulray <Stable Master>
2. 10053
3. Nie możnia z nia porozmawiać. To jest trener do jazdy. Myślę, że wiecej jest takich NPC od jazdy ze nie można z nimi porozmawiać.
4.http://www.wowhead.com/npc=10053/anya-maulray

**Comment by ravel1** [comment]
To nie jest trener do jazdy. Dodane itemy do sprzedaży.
