### ISSUE TITLE
NPC: Anette Williams <Bat Handler>

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#1062]
1.Anette Williams <Bat Handler>
2. 43124
3. Nie da sie od niej polecieć. Taki przypadek może mieć kilku Flay Masterów.
4. http://www.wowhead.com/npc=43124/anette-williams

**Comment by ravel1** [comment]
Problem występował u wszystkich "Bat Masterów" - naprawione ;)
