### ISSUE TITLE
Raid: The Obsidian Sanctum (Mount loot)

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#1070]
1. The Obsidian Sanctum 
2.ID Boss : 28860 ID Mounta  [Reins of the Black Drake]:43986 ID Mounta Reins of the Twilight Drake: 43954
3. Nie dropi z tego bosa  [Sartharion]. To sa 2 mounty na 10 i 25. Według tego filmu: https://www.youtube.com/watch?v=aHXGriMKtws  loot jest 100%. Zrobilismy go juz dwa razy i nic nie wypadło.
4. Link Raidu: http://www.wowhead.com/the-obsidian-sanctum
   Link Bossa: http://www.wowhead.com/npc=28860/sartharion
  Link 1 mounta: http://www.wowhead.com/item=43986/reins-of-the-black-drake
  Link 2 mounta: http://www.wowhead.com/item=43954/reins-of-the-twilight-drake

**Comment by thomas33** [comment]
Testowałem 5x na 10 i 25 i za każdym razem wypadł mount. Musiałeś zabić przez przypadek jakiegoś smoka.
