### ISSUE TITLE
Lost in the Floods

### ISSUE THREAD

**Issue by Icelandman** [Blackhandpl/bugtracker#108]
1.Lost in the Floods
2. 25187
3. po uzyciu lornetki na wiezy nie pokazuje nam gdzie znajduja sie dani npc ktorzy z koleji daja nam rowniez questy
4.http://www.wowhead.com/quest=25187/lost-in-the-floods

**Comment by grzewal1** [comment]
trzeba wejść do środka wieży i pokazuje gdzie są npc'e
