### ISSUE TITLE
Saurfang's Blessing NPC

### ISSUE THREAD

**Issue by Mendalista** [Blackhandpl/bugtracker#1093]
Brak NPC do oddania Qesta "Saurfang's Blessing"
Powinien znajdować się gdzieś przy Warchefie w Ogrimarze.
http://www.wowhead.com/quest=13189/saurfangs-blessing

**Comment by ravel1** [comment]
Questa powinno dać się również oddać u niego: http://www.wowhead.com/npc=39605/garrosh-hellscream
Zrobione
