### ISSUE TITLE
The Power Of Light 24528

### ISSUE THREAD

**Issue by Elthill** [Blackhandpl/bugtracker#1094]
1.The Power Of Light
2.ID: 24528
3.Opis: Mam się nauczyć Seal of Command i użyć na manekinie. Nie mam takiego skilla.
4.Link: http://www.wowhead.com/quest=24528/the-power-of-the-light

**Comment by ravel1** [comment]
Changelog blizzarda:
"Seal of Command - Patch 7.0.3 (2016-07-19): Removed."
Na przyszłość sprawdź najpierw jak powinno wszystko działać, a dopiero potem zgłaszaj.
Quest został wyłączony.
