### ISSUE TITLE
 Valadar Starsong

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#11]
1.  Valadar Starsong
2. 15864
3. Nie działa sklep
  Nie działa opcja rozmowy cyt: " Farewell. "
4. https://www.wowhead.com/npc=15864/valadar-starsong#starts

Moonglade

**Comment by grzewal1** [comment]
Sklep dodany, dodana creatura została usunięta, npc pojawia się tylko przy evencie Lunar Festival
