### ISSUE TITLE
Investigate An'daroth

### ISSUE THREAD

**Issue by illiachenvar** [Blackhandpl/bugtracker#11]
1. Investigate An'daroth
2. quest=9160
3. Licznik zabitych sentineli wariuje, kiedy jest 12/12 nagle resteuje się na 0/12. Nie zostaje zaliczona część z " Investigate An'daroth" pomimo łażenia po całym terenie.
4. http://www.wowhead.com/quest=9160/investigate-andaroth

**Comment by thomas33** [comment]
#280
