### ISSUE TITLE
[Quest] Caligraphed Note

### ISSUE THREAD

**Issue by RoninVmaxPl** [Blackhandpl/bugtracker#1131]
zadanie caligraphed note  nie można przeczytać tej kartki i zadanie się nie zalicza 
Wowhead link: http://www.wowhead.com/item=85203/calligraphed-note

**Comment by Harertz** [comment]
Quest na monka, a dostaje też go tauren druid... Do wywalania dla taurena druida

**Comment by ravel1** [comment]
Może podasz Questa? 🤕
