### ISSUE TITLE
Other: Reputacja, brak npc

### ISSUE THREAD

**Issue by Harertz** [Blackhandpl/bugtracker#1139]
Nie nabija nam reputacji robiąc questy... Przez co chyba nie widać niektórych npc.

**Comment by Harertz** [comment]
Dałem sobie reputacje komendą i mimo to nadal nie ma npc. Mam questa do oddania u NPC a go nie widać... Dopiero po wlaczeniu GM mode jest.

**Comment by ravel1** [comment]
Brak NPC nie wynika z braku reputacji tylko nie zrobieniem chaina itp.

**Comment by Harertz** [comment]
Właśnie chain zrobiony... Bo miałem zaznaczone na mapie znaczek by oddać questa do NPC i go nie było.. Dopiero po GM mode był.

**Comment by ravel1** [comment]
Repa nie ma na to wpływu.

**Comment by Harertz** [comment]
To co to może być?

**Comment by ravel1** [comment]
Nie wszystkie questy nie dają repy, dlatego zrób zgłoszenie jeszcze raz z questem, który tej repy nie daje.
