### ISSUE TITLE
[QUEST]Palm of the tiger

### ISSUE THREAD

**Issue by Ilmefy** [Blackhandpl/bugtracker#1162]
Description: 
Current behaviour: mozna go wziac jako paladyn(nie wiem jak z reszta klas) 
Expected behaviour: Tylko monk moze wziac tego questa
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=31142/palm-of-the-tiger

**Comment by ravel1** [comment]
"This quest was marked obsolete by Blizzard and cannot be obtained or completed"
