### ISSUE TITLE
Return to Blam

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#119]
1. Return to Blam
2. 27794
3. Brak misji
4. https://www.wowhead.com/quest=27794/return-to-blam

Badlands

**Comment by grzewal1** [comment]
po oddaniu misji 27912 dostajemy misję Return to Blam

**Comment by Mottomi3** [comment]
ta misja była wcześniej wykonana, sprawdź jeszcze raz
