### ISSUE TITLE
Resurrect po śmierci

### ISSUE THREAD

**Issue by Kirialaa** [Blackhandpl/bugtracker#12]
1. Resurrect
   2.
   3.Po śmierci w początkowej lokacji Humanów gdy użyłem opcji ressurect moja dusza została przeniesiona do cmentarza w westfall
2. Dusza postaci powinna zostać przeniesiona do najbliższego cmentarza

**Comment by Kirialaa** [comment]
Nie wiem czy ma to coś wspólnego ale na innym serwerze miałem to samo ( z tym że grałem worgenem)
a gdy teraz padłem to już normalnie do najbliższego cmentarza dostałem tp, więc można zamknąć ;)

**Comment by thomas33** [comment]
**Naprawione.**
