### ISSUE TITLE
Quest: Burn it up...

### ISSUE THREAD

**Issue by Seifero** [Blackhandpl/bugtracker#1201]
Description: Nie działa. Nie da się podpalić dział. Można rzucić pochodnię ale nie wywołuje żadnej reakcji.
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=10087/burn-it-up-for-the-horde

**Comment by thomas33** [comment]
#847
