### ISSUE TITLE
The Art of War

### ISSUE THREAD

**Issue by dexiu22** [Blackhandpl/bugtracker#1225]
Description: The Art of War
Current behaviour:  Brak możliwości rozmowy z nazgrimem 
Expected behaviour: Brak możliwości rozmowy z nazgrimem 
Steps to reproduce the problem: Brak możliwości rozmowy z nazgrimem 
Wowhead link: http://www.wowhead.com/quest=29612/the-art-of-war

**Comment by thomas33** [comment]
#213
