### ISSUE TITLE
[quest]Demon Souls

### ISSUE THREAD

**Issue by Tower-Erst** [Blackhandpl/bugtracker#1242]
Description: Niedziałający quest item
Current behaviour: Po zabiciu mobów, nie da się wykraść ich dusz.
Expected behaviour: Po zabiciu i użyciu quest itemu powinniśmy zabrać duszę mobów, które zginęły w zasięgu działania quest itemu
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=37653/demon-souls

**Comment by thomas33** [comment]
#383
