### ISSUE TITLE
Spellpower/dmg  ze spelli/stama/Ele shaman

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1253]
Description: zauwazżyłem grając ele shamanem  ze z każdym level coraz  mniej bije w przeciwnikow jak miałem 25 lvl to bilem zamiast 111  to 70 teraz jak mam 26  powinienem bic  po 119 a  bije po  60  z lighting bolta  podejrzewam ze  zresztą  spelli tez  tak jest bo bije coraz mniej, oraz  stamina i spell power  nie zwieksza misie proporcjonalnie z lvl
Relchak shaman
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link:

**Comment by ravel1** [comment]
DMG zadawany przez shamana działa poprawie.
