### ISSUE TITLE
Desolation hold inspection(quest)

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1256]
Description: wygląda  to tak mamy dojść do npc  pogadać  znim i wysluchac  go i quest powinien się zaliczyć  ale  po kliknieciu na okno dialogu npc  nie chce  rozmawiać  i quest niechce się zaliczyc
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=24577/desolation-hold-inspection

**Comment by thomas33** [comment]
#164
