### ISSUE TITLE
Quest (parts-is-parts)

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1257]
Description: to tak na polu bitwy maja  być  zwloki albo sami musi zabic  żołniezy by następnie ich poćwiartować ale niestety zadenz  tych scenariuszy nie działa  questa się nie da  wykonać poprostu
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=24619/parts-is-parts

**Comment by thomas33** [comment]
#166
