### ISSUE TITLE
Quest flightmare

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1258]
Description: To tak na polu bitwy powinny być gryfy na gryfach krasnale  i za pomoca  quest itema  powinniśmy ściągać  gryfa i npc  na dol problem polega w tym ze na całym polu bitwy jest az  1  gryf  w dodatku bez  krasnoluda  i quest item nie działa na grafa  gryf nie jest przyciągany ku ziemi tylko sobie dalej  lata  oraz  npc wogole nie ma na gryfie  nie ma go też nigdzie wiec quest nie można wykonac
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link:

**Comment by Relchak** [comment]
http://www.wowhead.com/quest=24631/flightmare

**Comment by thomas33** [comment]
#704
