### ISSUE TITLE
Skill ele shaman (Earth Elemental )

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1263]
Description: teraz  tak  skill powinien przyzywać  earth elementala Który walczy po mojej stronie generuje  duże  agro ma skille  tanka generalnie takie własne  oraz  armor  resisty wiadomo, ale na tym serwerze  nic się niedzieje  po  uzyciu skilla  earth elementa  ale  gdy masz  stargetowanego przeciwnika  i używasz  tego skill to działa  to jak nie widzialny taunt  nie daje  zadnego efecktu nie zadaje obrazen po prostu pulla przeciwnika, zadnego  supporta  po twoim stronie no po prostu nie dziala
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/spell=198103/earth-elemental

**Comment by thomas33** [comment]
#287
