### ISSUE TITLE
quest burn it up... For the horde

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1269]
Description: to sprawa  wygląda  tak mam podejść  do 2  czolgow  alluchow  uzyc  itemu centranie na jego dupie  widać  animacje podpalania oraz jak ogien leci w czol  ale nie zalicza  questa  po wycastowaniu id odgłosie  wybuchu nie zalicza  zadnego czołgu po prostu nie jest możliwe do wykonania
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=10087/burn-it-up-for-the-horde

**Comment by Seifero** [comment]
Zgloszone tydzien wczesniej i nie naprawione

**Comment by thomas33** [comment]
#847
