### ISSUE TITLE
Verog the Dervish

### ISSUE THREAD

**Issue by Icelandman** [Blackhandpl/bugtracker#127]
1. Verog the Dervish
2. 34846
3. aby zabic Veroga nalezy najpierw zabic NPC Wyneth: id 34846 jednak nie ma jej w wyznaczonym miejscu gdzie powinna byc oraz w okolicy rowniez nie moglem jej znalezc po jej zabiciu Verog powinien pokazac sie link do npc Wyneth:http://www.wowhead.com/npc=34846/wyneth#screenshots
4. http://www.wowhead.com/quest=851/verog-the-dervish

**Comment by Survikrowa** [comment]
Fixed
