### ISSUE TITLE
QUEST Arelion's Secret

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1274]
Description:  questa  powinismy oddac  u chodzącego npc pomiędzy zangramasz a  falcon watch ale  nie możemy oddać  tego quest  npc  pod żadnym razem.
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=10286/arelions-secret

**Comment by thomas33** [comment]
https://zapodaj.net/be678dbedbd59.jpg.html
