### ISSUE TITLE
Quest Talbuk mastery

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1275]
Description: Talbuk mastery niedziała  moba niema  w lokalizacji podanej na mapie nie ma  go tez na obszarach poza  lokalizacja, jest nie możliwy do znalezienie co uniemożliwia  zdobycie itemy a tym samym ukończenie questa
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=9859/talbuk-mastery

**Comment by thomas33** [comment]
Nie wiem gdzie Ty łaziłeś ale npc ma się dobrze :D

https://zapodaj.net/1661294c92c96.jpg.html

**Comment by Relchak** [comment]
no dobra  mój blad    bo go nie widziałem ;p
