### ISSUE TITLE
King of Centaur Mountain

### ISSUE THREAD

**Issue by Icelandman** [Blackhandpl/bugtracker#128]
1. King of Centaur Mountain
2. 13995
3. Po rozpoczeciu questa u npc Gorgal Angerscar powinien udac sie na pobliską górę i tam powinnismy sie bronic przed atakami centaurów gdzie w ostatniej fali zabijamy Kurak w tej chwili npc daje tylko questa i nic wiecej nie idzie na gore nawet jak sami tam pojdziemy nie ma fall atakujacych 
   4.http://www.wowhead.com/quest=13995/king-of-centaur-mountain#videos

**Comment by grzewal1** [comment]
Quest jet uproszczony. Kurak stoi i zabicie powoduje zaliczenie questa
