### ISSUE TITLE
Skill druid Survival Instincts

### ISSUE THREAD

**Issue by morti1997** [Blackhandpl/bugtracker#1290]
Description: Skill Survival Instincts to skill ktory zapewnia aure do zadawania wiekszych obrazen o 50% przez 6sek
Current behaviour: Nie dziala
Expected behaviour: Dzialajacy skill ktory zapewnia aure
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/spell=61336/survival-instincts

**Comment by thomas33** [comment]
Reduces all damage you take by 50% for 6 sec.
