### ISSUE TITLE
Spell - Roll

### ISSUE THREAD

**Issue by 0xaros0** [Blackhandpl/bugtracker#13]
1. Roll
2. ID: 109132
3. Kiedy się go używa nic się nie dzieje ):
4. http://www.wowhead.com/spell=109132/roll

**Comment by Fatmousus** [comment]
Chciałem już o tym pisać, ale ktoś mnie wyręczył :)

**Comment by thomas33** [comment]
Naprawione (potrzebna kompilacja)
