### ISSUE TITLE
Quest The Crypt of Remembrance

### ISSUE THREAD

**Issue by Alivashtath** [Blackhandpl/bugtracker#1327]
Description: Nie da się wejść w interakcję z NPC Keleseth 
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=12715/the-crypt-of-remembrance

**Comment by Harertz** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1241
