### ISSUE TITLE
quets down to azsuna

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1345]
Description:  quest polega na tym żeby  polecieć z  khazdgarem do azhuny na moucie który on nam da
ale  zamiast leciec  jesteśmy teleportowani do azsuny oraz  quest się nie zalicza  czyli jest bug.
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=41220/down-to-azsuna

**Comment by grzewal1** [comment]
poprawiono
