### ISSUE TITLE
quest 37653 demon-souls

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1346]
Description: quest polega na tym ze na martwych ciałach  demonow trzeba  uzyc Przynic  nawet nie majac  ichw  targecie  quest itemu ale  to niedziala  gdy krysztal jest przyzwany nic się niedzieje  a quest wykonać się nie da
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=37653/demon-souls

**Comment by thomas33** [comment]
#383
