### ISSUE TITLE
quest ceremonial-drums

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1389]
Description: quest polega na zebraniu dużych średnich ( dzialaja  poprawnie  bez  zarzutow) oraz  dropic male  bebny z ukrytych w  bardzo widocznym stelcie  koboltow ale niestety kobolty nie dropia drumsow quest nie dziala
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=42622/ceremonial-drums

**Comment by Survikrowa** [comment]
Fixed
