### ISSUE TITLE
Morning Breeze Village

### ISSUE THREAD

**Issue by Fatmousus** [Blackhandpl/bugtracker#141]
1. Morning Breeze Village
2. ID: 29776
3. Po zaakceptowaniu tego questa Shang Xi (chyba tak miał) powinien mocami wiatru unieść nas na szczyt świątyni skąd będziemy mogli mostem przejść na zachód Wandering Isle'a. Tak się nie dzieje. Akceptuje tego questa i nic. Gracze grający pandareńczykami automatycznie utykają na wyspie na wieki, bo tylko wykonanie wszystkich questów pozwala im na opuszczenie wyspy.
4. http://www.wowhead.com/quest=29776/morning-breeze-village#comments

**Comment by thomas33** [comment]
#952
