### ISSUE TITLE
spell  Fire  elemental

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1414]
Description: spell polega na tym ze  przyzywamy greater  fire elemntala  co bije i używa  skilli i nie da się go kontrollowa  gdyż  jest jak automat. ale niestety gdy klikamy na spell  to nic się niedzije  w dotaku spell fire  elementala powinismy uzyc  bez problemu ale jednak pokazuje nam ze potrzebujemy targetu żeby uzyc ten spell a jest to blad
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/spell=198067/fire-elemental

**Comment by ravel1** [comment]
287
