### ISSUE TITLE
spell earth elemental 

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1415]
Description: problem wygląda  tak samo jak z  fire elemntal spellem no nie działa  niema  nic oraz potrzebujemy targetu co jest  bledem
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/spell=198103/earth-elemental

**Comment by ravel1** [comment]
#287
