### ISSUE TITLE
Muddy Crawfish

### ISSUE THREAD

**Issue by Jeodic** [Blackhandpl/bugtracker#143]
1. Muddy Crawfish
2. 42548
3. Nie można ich bić (nie da się ich namierzyć atakami, cały czas są zielone), przez co ukończenia questa "Crawfish Creole" (26226) jest niemożliwe.
4. http://www.wowhead.com/npc=42548/muddy-crawfish

**Comment by ravel1** [comment]
Nie powinno się ich bić tylko je zbierać. Zrobione tak jak być powinno.
