### ISSUE TITLE
Strategic Cuts

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#143]
1. Strategic Cuts
2. 28246
3. Brak misji u npc
Misja nie działa poprawnie, wszystkie npc są wrogo nastawione. Wilki w stajni atakują
Quest item nie działa
4. https://www.wowhead.com/quest=28246/strategic-cuts

Burning Steppes

**Comment by grzewal1** [comment]
poprawiono działanie questitem
