### ISSUE TITLE
Pushing Forward

### ISSUE THREAD

**Issue by Fatmousus** [Blackhandpl/bugtracker#15]
1. Pushing Forward
2. ID: 25792
3. Totemy powinny się zniszczyć po użyciu blisko nich runy ognia otrzymanej po zaakceptowaniu questa, ale tak się nie dzieje. Będąc przy tym zadaniu powiem, że tamtejsi Trollmane Scavengerzy i Trollmane Scout rzucają pociskiem nie mającym tekstury. A przypadkiem te trolle nie powinny walczyć z krasnoludami NPC respiącymi się w nieskończoność ?
4. http://www.wowhead.com/quest=25792/pushing-forward#comments

**Comment by thomas33** [comment]
#640

**Comment by Elthill** [comment]
Potwierdzam bug'a.
