### ISSUE TITLE
quest Soothing the Elements

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1537]
Description: 
Current behaviour: po przyzwaniu totemu nic sie nie dzieje zywiolaki go nie atakuja 
Expected behaviour: obrona totemu przed zywiolakami 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=13580/soothing-the-elements

**Comment by grzewal1** [comment]
powielony #806
