### ISSUE TITLE
Skalowanie Kontentu Pandaria

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1540]
Description: Otoz to teleportujac sie i ekspiac na Pandari mozna juz od 80 ma sie rozumiec , lecz gdy tam jestem to kazdy mobek niezaleznie gdzie jestem nie skaluje sie do mojego lvl tylko do poziomu mapki z dodatku 7.3 Gdzie NIEMA Skalowania - Jest to ciezkie w lewelowaniu kazdej postaci gdyz postac na 82 nie trafia mobka na 90 i jest lipa .  
Wowhead link: http://www.wowhead.com/news=277409/7-3-5-ptr-new-zone-and-dungeon-scaling-levels
![wowscrnshot_060118_142344](https://user-images.githubusercontent.com/39434742/40841132-e6feae60-6598-11e8-955d-064f2ea1478f.jpg)
![wowscrnshot_060118_142348](https://user-images.githubusercontent.com/39434742/40841137-ec0dc27e-6598-11e8-89d8-8d25eb0fdbca.jpg)
![wowscrnshot_060118_142354](https://user-images.githubusercontent.com/39434742/40841138-ecdea272-6598-11e8-995b-6bcde58ad5da.jpg)
![wowscrnshot_060118_142408](https://user-images.githubusercontent.com/39434742/40841142-f10e2714-6598-11e8-910e-5f2aca86ba8a.jpg)
![wowscrnshot_060118_143351](https://user-images.githubusercontent.com/39434742/40841149-f6a7de9a-6598-11e8-98b8-60f00637cfac.jpg)

**Comment by ravel1** [comment]
Pandaria również jest skalowana w Legionie.
