### ISSUE TITLE
Guest Bled Dry w Tanaan Jungle prosze o pomoc

### ISSUE THREAD

**Issue by morti1997** [Blackhandpl/bugtracker#1545]
Description: Nie dziala mi quest Bled Dry w tanaan Jungle, gdy otwieram klatke nie zalicza mi quest inni z gildi nie mieli tego problemu prosze o pomoc
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=34421/bled-dry

**Comment by thomas33** [comment]
#1514
