### ISSUE TITLE
Quest Hot Lava

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1593]
Description: 
Current behaviour:   nieprawidlowe dzialanie , klikajac na quest itamek pokazuje nam sie dzialanie obszarowe ale  po uzyciu na szczelinach nie zalicza nam questa 
Expected behaviour: podchodzimy do szczelin w ziemi pokazuje man sie raczka 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=13880/hot-lava

**Comment by grzewal1** [comment]
działa
