### ISSUE TITLE
[QUEST] A Taste Of Iron - ciagle nie dziala

### ISSUE THREAD

**Issue by mkquack** [Blackhandpl/bugtracker#1618]
Description: Zbugowane dzialko
Current behaviour: Nie da sie wsiasc do dzialka
Expected behaviour:  Da sie wsiasc do dzialka
Steps to resolve the problem:  relog*1000
Wowhead link: http://www.wowhead.com/g00/quest=34445/a-taste-of-iron?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLnBsLw%3D%3D&i10c.ua=1&i10c.dv=14

**Comment by calienta** [comment]
działko unosi się do góry i nie da się wsiąść do niego
