### ISSUE TITLE
Blaze of Glory

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#162]
1. Blaze of Glory
2. 34422
3. Nie dostajemy quest itemy
4. https://www.wowhead.com/quest=34422/blaze-of-glory

Tanaan Jungle

**Comment by Mottomi3** [comment]
dodać do db item 113191

**Comment by grzewal1** [comment]
item dodany do hotfixes, 
poprawiona liczba przedmiotów przekazanych graczowi (włożonych do toreb gracza) po zaakceptowaniu zadania.
