### ISSUE TITLE
Dalaran Brak portali 

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1632]
Description: portal
Current behaviour: jest tylko portal do stormwind
![wowscrnshot_060818_145841](https://user-images.githubusercontent.com/39797014/41159340-84a3380a-6b2c-11e8-9399-6f8a30c6f01c.jpg)

Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link:

**Comment by ravel1** [comment]
Portale są w innym miejscu..
