### ISSUE TITLE
lazy-peons

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1667]
Description: quest nie działa  poprawnie nie dość  ze  npc  przy 1  logu jest od zajebania to jeszcze po uzyciu q itemu nci się nie dzieje
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=5441/lazy-peons

**Comment by ravel1** [comment]
"This quest was marked obsolete by Blizzard and cannot be obtained or completed."
Quest został usunięty.
