### ISSUE TITLE
lost-in-the-floods

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1668]
Description:  quest nie działa  quest item nie działa  wogole oraz jak podchodzimi  do  1  z npc to powinismy mieć opcje  dialogowe  ale ich nei ma i nie ja dostać  od  npc pod questow  co sprawia ze jest on a  wykonalny
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=25187/lost-in-the-floods

**Comment by grzewal1** [comment]
Quest zalicza automatycznie bez oglądania prze lunetę
