### ISSUE TITLE
[Quest][Dustwallow Marsh] What's Haunting Witch Hill?

### ISSUE THREAD

**Issue by ghost** [Blackhandpl/bugtracker#167]
1)  What's Haunting Witch Hill?

2) ID: 27188

3) Po zabiciu NPCa Risen Spirit(ID:23554) nie pojawia się NPC(ID:23554), przez co nie zalicza zadania.

4) http://www.wowhead.com/quest=27188/whats-haunting-witch-hill

**Comment by grzewal1** [comment]
Po stronie Alli sprawdzony że działa
