### ISSUE TITLE
The View from Down Here

### ISSUE THREAD

**Issue by Fatmousus** [Blackhandpl/bugtracker#17]
1 The View from Down Here
2 ID: 28868
3. Coś dużo błędów z zadaniami u krasnoludów odnotowuje :( A ten błąd polega na tym, że zmniejszenie Frostmane Buildera nie wlicza się do zadania. Trzeba zmniejszyć 5, ale ani jeden nie wlicza się do zadania. A ci robotnicy powinni uderzać w ziemię.
4. http://www.wowhead.com/quest=28868/the-view-from-down-here

**Comment by thomas33** [comment]
#639
