### ISSUE TITLE
Vortex

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#173]
1. Vortex
2. 13886
3. Brak dymku u npc. Zapewne nie będzie skilli u stworka, którym mamy zabić elite- sprawdzić.
Brak npc do oddania misji 
4. https://www.wowhead.com/quest=13886/vortex

Ashenvale

**Comment by grzewal1** [comment]
Dymki działają, ale skille są za słabe na npc, przechodzi w niewrażliwość.
Quest po stronie hordy
https://www.wowhead.com/quest=13888/vortex
