### ISSUE TITLE
Blad dodawania PKT w Tailoring

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1733]
Description: Problem polega na niedodawaniu pkt za robienie Bolt of Emberslik Cloth a rowniez Emberslik Net
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/spell=74964/bolt-of-embersilk-cloth#taught-by-npc

**Comment by calienta** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1244
