### ISSUE TITLE
Blazing Barrier

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1736]
Description: Bladz polega na tym ze z talentem Blazing Soul tarcza jest praktycznie nie do zbicia gdy Mag bije enemy za 120k to tarcza sie regeneruje do calosci (160k absorbu) talent daje 40% powrotu i jest zbugowany daje nam za duzo absorbu. Dzieki czemu mozna samemu zbijac dungeony na poziomie MYTHIC
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/spell=235313/blazing-barrier

**Comment by thomas33** [comment]
Spell tymczasowo wyłączony
