### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by mkquack** [Blackhandpl/bugtracker#1753]
Description: skinning staje na 650 i nie idzie dalej pomimo ze odblokowany jest max skill 800
Current behaviour: nie da sie wbic skilla >650 pomimo zrobionego LegionSkinner
Expected behaviour: skinning do 800 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/skinning

**Comment by thomas33** [comment]
#1801
