### ISSUE TITLE
Bolyun

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#176]
1. Bolyun
2. 3698/34599
3. NPC mają fazy popyrtane. Przy oddaniu jednej z misji, powinni się podmienić- nie działa, przez co nie możemy oddać 1 misji i wziąć kolejnej.
4. https://www.wowhead.com/npc=34599/bolyun
https://www.wowhead.com/npc=3698/bolyun

Ashenvale

**Comment by grzewal1** [comment]
poprawione
