### ISSUE TITLE
quest The Perfect Poultice

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1777]
Description: quest item 
Current behaviour: na miejscu sa tylko 3 Verrall River Muck quest itemki do zbierania 
Expected behaviour: wiecej Verrall River Muck
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=27538/the-perfect-poultice

**Comment by calienta** [comment]
robiłem ten q kilka dni temu i było z 10 sztuk

**Comment by calienta** [comment]
sprawdzałem dziś (w hordzie http://www.wowhead.com/quest=26788/cementing-our-victory więc odpowiednik) i znalazłem 9 http://www.wowhead.com/object=204880/verrall-river-muck
