### ISSUE TITLE
Strike From Above

### ISSUE THREAD

**Issue by Fatmousus** [Blackhandpl/bugtracker#18]
1. Strike From Above
2. ID: 25841
3. Chyba macie problem z zadaniami, w których NPC musi coś powiedzieć i w tych zadaniach, w których trzeba użyć rzeczy otrzymanych od nich. Tym razem użycie flary w wyznaczonym miejscu nie wlicza się do zadania.
4. http://www.wowhead.com/quest=25841/strike-from-above

**Comment by thomas33** [comment]
#642
