### ISSUE TITLE
DK STARTOWA LOKACJA THE ENDLESS HUNGER

### ISSUE THREAD

**Issue by Malvarmo** [Blackhandpl/bugtracker#1802]
Description: Klucz nie uwalnia więźniów 
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=12848/the-endless-hunger

**Comment by calienta** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1587

**Comment by matt155** [comment]
Nie działa, nie da się użyć klucza, a jak raz się udało chyba fuksem to nie uwolniło więźnia.
