### ISSUE TITLE
quest Rescue Rangari

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1842]
Description: Npc
Current behaviour: brak interakcj z npc , do tego nie klecza nie mozna wykonac questa 
Expected behaviour: po rozmowie z npc  powinno zaliczac questa do tego npc powinny kleczec ,ukrywac sie przy krzakach
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=35050/rescue-rangari

**Comment by grzewal1** [comment]
zrobiono, ale bez klęczenia
