### ISSUE TITLE
quest Runas the Shamed

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1861]
Description: npc
Current behaviour: kiedy juz zbijemy +- pol zycia Runasowi ten wraca na swoj kocyk i z nami ani nie rozmawia ani nie idzie  kiedy wrocimy  do Projection of Senegoa  Runas juz tam stoi ale nie zalicza nam questa 
![wowscrnshot_063018_162726](https://user-images.githubusercontent.com/39797014/42126107-b1e9b9b2-7c82-11e8-805b-f3a5f5b68bd2.jpg)

Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=37957/runas-the-shamed

**Comment by thomas33** [comment]
#1352
