### ISSUE TITLE
quest Runas Knows the Way

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1862]
Description: npc 
Current behaviour: po kliknieciu na Runasa i wybraniu "fallow me" nic sie nie dzieje 
![wowscrnshot_063018_164039](https://user-images.githubusercontent.com/39797014/42126215-c53474d8-7c84-11e8-9d6b-617ac0c4e6c1.jpg)

Expected behaviour: Runas powinien chwile pogadac z Projection of Senegosa  po chwili wskoczyc na mana sebera i pojechac z nami 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=37857/runas-knows-the-way

**Comment by ravel1** [comment]
#1353
