### ISSUE TITLE
Profesja BS Legion GameObject Firnament Stone

### ISSUE THREAD

**Issue by Malvarmo** [Blackhandpl/bugtracker#1868]
Description:Nie wykrywa Firmament Stone przez co nie można craftowac itemow z http://www.wowhead.com/spell=192236/recipe-demonsteel-bar
Current behaviour: Stojąc przy Stone nie można wytworzyć Demonsteel Bar   <a href="https://ibb.co/fe5yzy"><img src="https://thumb.ibb.co/fe5yzy/Wo_WScrn_Shot_070118_093050.jpg" alt="Wo_WScrn_Shot_070118_093050" border="0"></a>
Expected behaviour: Stojąc przy Stone można wytworzyć Demonsteel Bar
Steps to reproduce the problem: 
Wowhead link: Linku nie mogę znalesc

**Comment by calienta** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1856 zgłaszałem
