### ISSUE TITLE
quest Demon Souls

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1872]
Description: quest item 
Current behaviour: po zabiciu paru demonow i uzyciu soul gemu pokazuje sie animacja  enchantingu i nic wiecej nie zalicza questa do tego dh przy obozie nie walcza 
![wowscrnshot_070118_195220](https://user-images.githubusercontent.com/39797014/42137215-c33cb854-7d68-11e8-8c20-7b7730ac6551.jpg)

Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=37653/demon-souls

**Comment by calienta** [comment]
zgłaszane https://github.com/Blackhandpl/bugtracker/issues?utf8=%E2%9C%93&q=Demon+Souls

**Comment by thomas33** [comment]
#383
