### ISSUE TITLE
DK quest Into the Realm of Shadows

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#1875]
Description: 
Current behaviour: Salanar the Horseman nie wysyla nas do wymiaru cieni ,kon i jezdziec  sa w relamie zywych niestety  jesli  jezdzca zabije sie  przrzez przypadek  przed questem na konia quest jest nie wykonalny a kania nie mozna nawet targetowac 
relam pojawia sie w Acherusie w chwili gdy podchodzimy do lk nie mozna uzywac teleportu 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: 
http://www.wowhead.com/quest=12687/into-the-realm-of-shadows

**Comment by ravel1** [comment]
Nie przenosi w faze ale koń sobie jeździ i po zabiciu jeźdźca można wrócić na górę i dokończyć questa.
