### ISSUE TITLE
the-art-of-war

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1876]
Description:  quest polega na tym ze  w  ogrimarze  udajemy się do gromash holdu i musimy odac  quest nazgrimowi ( znaczy się musimy z nim wejść  w inter  akcje aby zaliczyć  questa  ale nawet po zajściu w inter akcje  nic się nie dzieje zadnych rozmow  opcji dialogowych itp. nic) ale quest po prostu nie działa nie da się  go wykonać zaliczyc
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=29611/the-art-of-war

**Comment by calienta** [comment]
zgłaszane https://github.com/Blackhandpl/bugtracker/issues?utf8=%E2%9C%93&q=The+Art+of+War

**Comment by thomas33** [comment]
#213
