### ISSUE TITLE
bled-dry horda

### ISSUE THREAD

**Issue by Relchak** [Blackhandpl/bugtracker#1879]
Description:  quest znowu dalej nie działa Plus klatka jest po francuski jakims  hujem oraz w kaltce nie ma orcow nic  klatka się otwiera( obydwie klatki bo sa  2 do uzycia  )  i nie zalicza nam się quest a poprzednio quest dzialala bardzo dobrze i nawet orci były w klatkach teraz  się zjebal.
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=34421/bled-dry

**Comment by calienta** [comment]
4x zgłosiłeś https://github.com/Blackhandpl/bugtracker/issues?utf8=%E2%9C%93&q=bled+dry

**Comment by thomas33** [comment]
#1514
