### ISSUE TITLE
Loot w grze

### ISSUE THREAD

**Issue by hipolit** [Blackhandpl/bugtracker#188]
Czasami, gdy chce się podnieść loot z NPC widzimy item, ale wyskakuje komunikat "Already looted". To dzieje się z różnymi itemami ze zwykłych mobków, ale też na dungeonach. Pomagałem zrobić dzisiaj dungeana i z żadnego bosa nie dała się podnieść itemu, loot był ustawiony na free for all i zawsze wyskakiwał ten sam komunikat "Already looted". 

Dodam jeszcze, że roll o itemy nie działa, nawet nie wyskoczyło okienko z need i greed, a na itemach był komunikat, że trzeba czekać bo jest losowanie (nie pamietam dokładnego komunikatu).

**Comment by Harcok66** [comment]
Możesz zauważyć, że item graficznie wpada do twojego bagu ale realnie do niego nie trafia dlatego wskakuje ten napis.
