### ISSUE TITLE
[Quest] Lazy Peons

### ISSUE THREAD

**Issue by Sandroel** [Blackhandpl/bugtracker#1903]
[Quest] Lazy Peons
ID: 25134
Zadanie można dwa razy wziąć oraz, gdy przedmiot trzeba użyć na peona to pisze invalid target.
Można poprawnie przyjąć misje.
http://www.wowhead.com/quest=25134/lazy-peons

**Comment by Survikrowa** [comment]
This quest was marked obsolete by Blizzard and cannot be obtained or completed.
Quest zostanie usunięty za niedługo

**Comment by Sandroel** [comment]
ok.
