### ISSUE TITLE
[QUEST] The Embalmer's Revenge

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1904]
Description: problem polega na tym ze Mini boss to q jest poza miejscem gdzie powinien byc i jest on neutralny , mozna zagadac ale nic niema , jest to ostatni q do questline w achivie wiec powinien dzialac
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=26727/the-embalmers-revenge
![wowscrnshot_070918_131157](https://user-images.githubusercontent.com/39434742/42447435-2637ab64-837a-11e8-95b2-5bc869a1ead8.jpg)
![wowscrnshot_070918_131205](https://user-images.githubusercontent.com/39434742/42447436-26630458-837a-11e8-8e27-e4921ee422b0.jpg)

**Comment by Survikrowa** [comment]
Fixed
