### ISSUE TITLE
Oil Canister

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#193]
1. Oil Canister
2. 34345
3. Atakują nas, czego raczej nie powinny robić- powinny być na plecach https://www.wowhead.com/npc=34353/kromgar-incinerator
4. https://www.wowhead.com/npc=34345/oil-canister#screenshots

Stonetalon Mountains

**Comment by grzewal1** [comment]
Należą do Hordy i Alliance atakują. Czym grałeś?

**Comment by Mottomi3** [comment]
Frakcja wroga alliance, mozliwe że horda.
