### ISSUE TITLE
Class Hall NPC Flamesmith Lanying <Earthen Ring Quartermaster>

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1936]
Description: NPC w class hall powinien sprzedawac Set na 110 lvl , upgrade setu zabawki i przedmioty startowe w legion Earthen Ring Scepter , Earthen Ring Aegis i Earthen Ring Mace lecz gdy probuje wejsac w interakcje z npc ten ma NIC nie da sie nic kupic bo tam sklepu NIEMA 
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/npc=112318/flamesmith-lanying#sells

**Comment by Survikrowa** [comment]
Fixed
