### ISSUE TITLE
Skinning Cliffwing Hippogryph

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1956]
Description: Mob do questa ze skinningu , potrzebne itemy leca z oskorowania tego to moba a skinowac sie nie da
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/npc=89386/cliffwing-hippogryph#skinning

**Comment by Survikrowa** [comment]
Fixed
