### ISSUE TITLE
BRAK Npc - Crab Rider Grmlrml

### ISSUE THREAD

**Issue by Zugg12321** [Blackhandpl/bugtracker#1968]
Description: Spawn jak to pisze Ravel Nie ma go na serwie wiec prosze by byl jest potrzebny do 2 q + dropi itemki fajne
Current behaviour: ID npc  =  97933
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/npc=97933/crab-rider-grmlrml#drops

**Comment by Survikrowa** [comment]
Fixed by Grzewal
