### ISSUE TITLE
NPC: Clopper Wizbang

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#2000]
Description: Powinien sprzedawać przedmioty, a klikająć nic nie pokazuje, tzn ma questy i można je ukończyć, ale nie ma opcji sprzedaży graczowi.
The Bloodwash (plaża, skorupa żółwia), Bloodmyst Isle
NPC ID: 17421
Wowhead link: https://www.wowhead.com/npc=17421/clopper-wizbang

**Comment by Survikrowa** [comment]
Fixed
