### ISSUE TITLE
The Maelstrom

### ISSUE THREAD

**Issue by hipolit** [Blackhandpl/bugtracker#201]
1)  The Maelstrom

2) ID: 27203

3) Po użyciu przedmiotu powinien pokazać się filmik, a postać powinna się przenieść do Deepholm. Natomiast pojawia się tylko czarny ekran i trzeba się wylogować, żeby dało się dalej grać.

4) http://www.wowhead.com/quest=27203/the-maelstrom

**Comment by thomas33** [comment]
#563
