### ISSUE TITLE
zbugowany feral

### ISSUE THREAD

**Issue by jaggurt** [Blackhandpl/bugtracker#2015]
Description: 
Ferocious Bite-po dostaniu tej umiejętności podczas nabicia do niej potrzebnych combo pointów nie moge jej używać oprócz tego po każdym relogu znika paska umiejętności jak i z spell booka dopiero po dostaniu lvla pojawia się znowu ale nadal nie jest do użytku.
Rake-nie można używać umiejętności i dzieję się z nią tak samo jak z  Ferocious Bite 
Shred-również to samo jak Rake
Rip-dzieje się to samo co z poprzednimi umiejętnościami 
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: 
Ferocious Bite- https://www.wowhead.com/spell=22568/ferocious-bite
Rake- https://www.wowhead.com/spell=1822/rake
Shred- https://www.wowhead.com/spell=5221/shred
Rip- https://www.wowhead.com/spell=1079/rip

**Comment by ravel1** [comment]
Wszystko co opisałeś działa bez żadnego problemu.
Stworzyłem 10 postaci i w żadnej problem nie występował.
Usuń folder Cache z folderu z WoWem i zobacz czy problem będzie nadal występował.
