### ISSUE TITLE
Portal do Blasted Lands

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#2020]
Description: Najeżdżając na portal pisze coś po francusku :D zamiast Portal to Blasted Lands.
"Portail vers la peninsule des Flammes infernales"
Tak jest i w Exodar i w Darnassus.

**Comment by ravel1** [comment]
Wszystkie portale do Blasted Lands mają właściwą nawę. Usuń folder cache i uruchom gre ponownie.
