### ISSUE TITLE
Brak Fly Mastera

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#2036]
Description:  brak npc
Current behaviour: w ilidari dtand i azurewing repose  nie ma fly masterow 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: 
https://www.wowhead.com/npc=88110/izal-whitemoon
https://www.wowhead.com/npc=90556/dagrona

**Comment by ravel1** [comment]
Proszę o bardziej szegułowe informacje wraz z linkiem z wowheada do brakującego NPC.
