### ISSUE TITLE
[QUEST] The stolen letters

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#2061]
The stolen letters
26667
Po podniesieniu listu nie zalicza nam misji, nie dodaje objektu
Przedmiot ktory podnosimy aby dostac list > https://www.wowhead.com/object=204462/pile-of-scraps
Przedmiot ktory powinnismy dostac > https://www.wowhead.com/item=59357/a-slashed-bundle-of-letters#objective-of
Quest>
https://www.wowhead.com/quest=26667/the-stolen-letters

**Comment by grzewal1** [comment]
mam quest zaliczony, cały Duskwood został sprawdzony i questy działają
