### ISSUE TITLE
[QUEST] Looks Like a Tauren Pirate to Me

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#2079]
Looks Like a Tauren Pirate to Me
26630
Nie dziala czesc questa w ktorej mamy podejsc do Fleet Master Seahorn (2487) i powiedziec "Here its IS" (jest taka opcja rozmowy, ale nic sie nie dzieje)
 npc  https://www.wowhead.com/npc=2487/fleet-master-seahorn
 quest  https://www.wowhead.com/quest=26630/looks-like-a-tauren-pirate-to-me#screenshots

**Comment by Mottomi3** [comment]
Moj blad, nie mialem pewnego przedmiotu, ale mimo to npc nic nie robi.
Quest nie dziala z innego powodu (inny npc z kapeluszem jest zbugowany)

**Comment by grzewal1** [comment]
duplikat #718
