### ISSUE TITLE
[QUEST] Details of the Attack

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#2083]
Details of the Attack
26612
Brak tego przedmiotu  59145 https://www.wowhead.com/item=59145/bloodsail-orders
Powinien lezec na skrzynkach kolo pierwszego namiotu 
quest -  https://www.wowhead.com/quest=26612/details-of-the-attack
przedmiot - https://www.wowhead.com/item=59145/bloodsail-orders

**Comment by grzewal1** [comment]
duplikat #799
