### ISSUE TITLE
[QUEST] Mark V is Alive!

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#2108]
Mark V is Alive!
10191
Quest mozemy wziasc u 2 npc, gdzie powinien byc tylko u 1.Tylko u jednego quest sie odpala.
Po ukonczeniu oprowadzania robota po wertepach misji nam nie zalicza.
Usunac mozliwosc wziecia misji od tego npc > 19578
Dodac zaliczanie misji by moc u niego ja oddac  ^up^
https://www.wowhead.com/quest=10191/mark-v-is-alive

**Comment by Survikrowa** [comment]
Fixed
