### ISSUE TITLE
Force Commander Valen

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#214]
1. Force Commander Valen
2. 41229
3. NPC nie daje nam misji https://www.wowhead.com/quest=25852/alls-clear
4. https://www.wowhead.com/npc=41229/force-commander-valen

Stonetalon Mountains

**Comment by grzewal1** [comment]
Czy zrobiłeś quest [https://www.wowhead.com/quest=25851/dances-with-grimtotem](url)

**Comment by Mottomi3** [comment]
Tak


wt., 26 sty 2021, 07:12 użytkownik grzewal1 <notifications@github.com>
napisał:
