### ISSUE TITLE
Hierophant Malyk

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#215]
1. Hierophant Malyk
2. 41487
3. Sprawdzić czy npc daje misje:
https://www.wowhead.com/quest=25930/ascending-the-vale
https://www.wowhead.com/quest=25938/help-for-desolace
Nie dostałem obu
4. https://www.wowhead.com/npc=41487/hierophant-malyk

Stonetalon Mountains

**Comment by grzewal1** [comment]
Aby dostać quest [https://www.wowhead.com/quest=25930/ascending-the-vale]() trzeba ukończyć [https://www.wowhead.com/quest=25925/thaldarahs-vengeance]().

**Comment by Mottomi3** [comment]
Miałem ukończoną tę misję.

**Comment by grzewal1** [comment]
w bazie nie widać że masz ukończoną misję o zgłaszałeś wcześniej że nie działa :) https://github.com/Blackhandpl/bugtracker/issues/203
