### ISSUE TITLE
The Emblazoned Runeblade

### ISSUE THREAD

**Issue by lewap24pl** [Blackhandpl/bugtracker#215]
1. [The Emblazoned Runeblade]
2.ID:12619
3.Po podniesieniu  itemu questowego BATTLE- WORN SWORD nie zlaicza questa i nie można oddać do NPC
4.http://www.wowhead.com/quest=12619/the-emblazoned-runeblade

**Comment by hipolit** [comment]
Po podniesieniu przedmiotu trzeba go jeszcze użyć na kuźni (trzeba chwile poczekać bo nie ma paska ładowania). Przed chwilą zrobiłem ten quest bez problemu.
