### ISSUE TITLE
[QUEST] Welcome to Gorgrond

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#2202]
Welcome to Gorgrond
35033
Nie ma opcji oddania questa u npc Rangari D'kaan (80921)
https://www.wowhead.com/npc=80921/rangari-dkaan#ends
https://www.wowhead.com/quest=35033/welcome-to-gorgrond#videos:id=127319

**Comment by Survikrowa** [comment]
Fixed
