### ISSUE TITLE
Undercity

### ISSUE THREAD

**Issue by hipolit** [Blackhandpl/bugtracker#222]
1) Undercity

2) ID: 68

3) Drzwi do windy do miasta są cały czas zamknięte.

4) http://www.wowhead.com/faction=68/undercity

**Comment by ravel1** [comment]
Jakie drzwi? Jeżeli chodziło Ci o drzwi do windy to jest to zrobione. Jeżeli o inne to zrób ponownie zgłoszenie z Print Screenem i dokładnie opisz, o które drzwi Ci chodzi.
