### ISSUE TITLE
Taking a trip to the top of the tank

### ISSUE THREAD

**Issue by Dariusz861013** [Blackhandpl/bugtracker#2227]
Description: 
Current behaviour: nie można ukończyć questa - krasnala, do którego oddaje się zadanie, nie ma na dużym czołgu.
Expected behaviour: możliwość ukończenia questa - naprawa problemu
Steps to reproduce the problem: 
Wowhead link: https://www.wowhead.com/quest=35747/taking-a-trip-to-the-top-of-the-tank

**Comment by Survikrowa** [comment]
Fixed
