### ISSUE TITLE
[Quest] Into the Fray

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#2229]
Description: Nie mogę oddać questa, bo nie ma Kayna Sunfury
Wowhead link: https://www.wowhead.com/quest=44137/into-the-fray
https://www.wowhead.com/npc=89362/kayn-sunfury

**Comment by Survikrowa** [comment]
Fixed

**Comment by matt155** [comment]
Kayn jest, ale oddać dalej nie można. Nie wiem czy po prostu powinienem mieć opcję rozmowy czy od razu oddać, ale się nie da.
