### ISSUE TITLE
 [The Hatchery Must Burn]

### ISSUE THREAD

**Issue by lewap24pl** [Blackhandpl/bugtracker#227]
1. [The Hatchery Must Burn]
2.ID:25810
3.Brak NPC
4.http://www.wowhead.com/quest=25810/the-hatchery-must-burn

**Comment by ravel1** [comment]
NPC znajdował się w odpowiednim miejscu, lecz portal do lokacji w której NPC był nie działał. 
Opisuj błędy poprawnie bo to już nie pierwszy raz...
