### ISSUE TITLE
Hearthstone

### ISSUE THREAD

**Issue by hipolit** [Blackhandpl/bugtracker#239]
1)  Hearthstone

2) ID: 6948

3) Hearthstone czasem (na około 40 lvl) sam przestawia się do Warchief's Lookout na The Lost Isles (lokacja startowa goblinów) i nie da się już opuścić lokacji. Postać zostaje uwięziona (teleport na stronie też nie działa).

4) http://www.wowhead.com/item=6948/hearthstone

**Comment by thomas33** [comment]
#119
