### ISSUE TITLE
[ Westfall][Quest]Secrets of the Tower

### ISSUE THREAD

**Issue by Lamoraaaa** [Blackhandpl/bugtracker#2506]
Description: 
Current behaviour: na gorze wierza jest pusta
Expected behaviour: powinnismy byc swiatkami stotkania 
Steps to reproduce the problem: 
Wowhead link: 
https://www.wowhead.com/quest=26290/secrets-of-the-tower#videos

**Comment by grzewal1** [comment]
działa ale nie zgodnie z pierwowzorem, quest zalicza
