### ISSUE TITLE
Why is everything exactly like Dufernst Legioncore git

### ISSUE THREAD

**Issue by acidmanifesto** [Blackhandpl/bugtracker#251]
Level 90 boost in the bshop was a dead give away.
Alot of spp stuff is present on your server as well.

https://github.com/dufernst/LegionCore-7.3.5/commit/60ebad5598914a0aabf342a35721ed120f235155

**Comment by ravel1** [comment]
Blackhand core is based on Ashamane and clean TC.

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/116008394-498b7400-a5e2-11eb-9160-6633bea70efc.png)
Thats a lie.
Your battlecoin and level 90 boost is the same thing and the only thing working. Prove me wrong. add one item in your bshop category. fill out the "donate" collumn. prove me wrong.

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/116009370-3cbd4f00-a5e7-11eb-938c-22d33912a4d8.png)
https://youtu.be/Ofgf4ya4UBw

**Comment by acidmanifesto** [comment]
I actually created the tabled top dancer back in feburary of 2020
https://www.youtube.com/watch?v=Ofgf4ya4UBw

**Comment by kiazmey** [comment]
busted!
