### ISSUE TITLE
3 Quests in Dustwallow not working

### ISSUE THREAD

**Issue by Roblox696969playerbis** [Blackhandpl/bugtracker#252]
1. (The witch's Bane + The Black Shield + Jarl Needs eye): 
2. (ID): 
3. (Dont drop for quest completion, all in Dustwallow Marsh): 
4. (Wowhead link):

**Comment by grzewal1** [comment]
Duplicate  https://github.com/Blackhandpl/bugtracker/issues/232 The witch's Bane
Fix chance drop https://www.wowhead.com/quest=27184/jarl-needs-eyes
https://www.wowhead.com/quest=27254/the-black-shield the whole chain is passable
