### ISSUE TITLE
[SPELL][WARRIOR] Heroic Leap

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#254]
1. Heroic Leap
2. 134787
3. powinnismy po wskazaniu miejsca wskoczyc a zarazem jest tylko do wyboru kierunek skoku ale nie wskakuje w wskazane miejsce
4. http://www.wowhead.com/spell=134787/heroic-leap

**Comment by thomas33** [comment]
Powinno byc ok po kompilacji
