### ISSUE TITLE
Quest Nagrand chain arena

### ISSUE THREAD

**Issue by Samerhajj** [Blackhandpl/bugtracker#254]
1. (Name of Quest, Spell, object etc.): The Ring of Blood: The final challenge
2. (ID): 9977
3. (Description): Killing Mogul does not credit you the kill. hence you can't finish the quest chain
4. (Wowhead link): https://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge

**Comment by grzewal1** [comment]
fixed
