### ISSUE TITLE
[Quest][Duskwood] Classy Glass

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#258]
1. (Name of Quest, Spell, object etc.): Classy Glass
2. (ID): 26685
3. (Description): Ogre's Monocle doesn't drop from Zzarc'Vul. Drop rate is 97%.
4. (Wowhead link): https://www.wowhead.com/quest=26685/classy-glass

**Comment by grzewal1** [comment]
fix drop rate to 97%
