### ISSUE TITLE
[quest] Duskwing, Oh How I Hate Thee...

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#26]
1. (Nazwa Questa, Spella, objektu itp.): [quest] Duskwing, Oh How I Hate Thee...
2. (ID): quest=27523
3. (Opis błędu): nie działa za dobrze item który trzeba użyć do ściągnięcia moba z powietrza na ziemie
4. (Link wowhead): https://www.wowhead.com/quest=27523/duskwing-oh-how-i-hate-thee

**Comment by grzewal1** [comment]
poprawione
