### ISSUE TITLE
Quest : Frost Nova

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#269]
1-Nazwa questa - Frost Nova
2-ID - 10068
Opis:  [	Practice Frost Nova (2)]  Używając umiejętności na kukłach nie zalicza mi misji [mag sunstrider isle blood elf]
link wowhead: [ http://www.wowhead.com/quest=10068/frost-nova ]

**Comment by thomas33** [comment]
**Naprawione.**
