### ISSUE TITLE
[NPC] Delios Silverblade

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#27]
1. (Nazwa Questa, Spella, objektu itp.): [NPC] Delios Silverblade
2. (ID): npc=43010
3. (Opis błędu): Wymaga testu . zdaje mi się że ma misję [quest] Charge! . zobaczę jeszcze warriorem czy przejdzie się to misje , na razie w poczekalni to zostawiam 
4. (Link wowhead): https://www.wowhead.com/npc=43010/delios-silverblade

**Comment by ravel1** [comment]
Ten npc nie daje żadnego questa
