### ISSUE TITLE
Marked Shot

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#270]
1. Marked Shot
2. 185901
3. Na szaro nie da sie wogole uzyc
4. http://www.wowhead.com/spell=185901/marked-shot

**Comment by nerv234** [comment]
Mogłeś od razu napisać że arcane shot nie aktywuje spella, takich zgłoszeń się oczekuje. Sprawdź z sidewindersami, + zrozum mechanike spella i zrób zgłoszenie o arcane shota.
