### ISSUE TITLE
[NPC] [The Cape of Stranglethorn] Ironjaw Behemoth (doubled npc)

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#275]
1. (Name of Quest, Spell, object etc.): Ironjaw Behemoth
2. (ID): 44113
3. (Description): The NPC Ironjaw Behemoth in Crystalvein Mine, (The Cape of Stranglethorn) is doubled on the same place and it's rather difficult to kill.
4. (Wowhead link): https://www.wowhead.com/npc=44113/ironjaw-behemoth

**Comment by grzewal1** [comment]
fixed
