### ISSUE TITLE
Artifact spawnrate

### ISSUE THREAD

**Issue by Tobywuan01** [Blackhandpl/bugtracker#278]
1. (Name of Quest, Spell, object etc.):  Dwarven Artifacts
2. (ID): 24477
3. (Description): The quest is working but there is not spawning that many at a time so maybe up the spawn rate ?
4. (Wowhead link): https://www.wowhead.com/quest=24477/dwarven-artifacts

**Comment by grzewal1** [comment]
diminished despawn
