### ISSUE TITLE
Spawntime for barrels

### ISSUE THREAD

**Issue by Tobywuan01** [Blackhandpl/bugtracker#279]
1. (Name of Quest, Spell, object etc.): First Things First: We're Gonna Need Some Beer
2. (ID): 24474
3. (Description): The quest is working but the barrels of beer take an absurd amount of time to respawn so even when ur doing it as 2 people it start getting annoying to wait
4. (Wowhead link): https://www.wowhead.com/quest=24474/first-things-first-were-gonna-need-some-beer

**Comment by grzewal1** [comment]
diminished despawn
