### ISSUE TITLE
Oddly-shaped stomach

### ISSUE THREAD

**Issue by hugyy59** [Blackhandpl/bugtracker#287]
1. (Name of Quest, Spell, object etc.): Oddly-shaped stomach
2. (ID): 
3. (Description): This item is a kind of lootbox but it gave me nothing. Should give many items ^^
4. (Wowhead link): https://fr.wowhead.com/item=129746/estomac-bizarrement-form%C3%A9#contains

**Comment by grzewal1** [comment]
in my opinion it is loot
