### ISSUE TITLE
[NPC][Eastern Plaguelands] Garginox - (an elite npc multiplied in area)

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#296]
1. (Name of Quest, Spell, object etc.): Garginox
2. (ID): 45681
3. (Description): Garginox (an elite npc) is multiplied in The Noxious Glade. I counted 5 of them, i didn't check all area, because 4 of them are almost in on spot.
4. (Wowhead link): https://www.wowhead.com/npc=45681/garginox

**Comment by grzewal1** [comment]
fixed
