### ISSUE TITLE
Thunderfist Gorilla

### ISSUE THREAD

**Issue by Youki1** [Blackhandpl/bugtracker#30]
1. Thunderfist Gorilla
2. 59742
3. Dropi Wristy Clothowe na 100lv  http://www.wowhead.com/item=116007/bracers-of-unending-consumption&bonus=0
4. http://www.wowhead.com/npc=59742/thunderfist-gorilla

Screen potwierdzający http://imgur.com/Zux8x4r

**Comment by ravel1** [comment]
Jesteś przykładem dla innych jak powinno zgłaszać się bugi. Świetna robota!
