### ISSUE TITLE
[QUEST] War on the Ramparts

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#301]
1. (Name of Quest, Spell, object etc.): War on the Ramparts
2. (ID): 29528
3. (Description): Gargolmar doesn't drop his hand
4. (Wowhead link): [https://www.wowhead.com/quest=29528/war-on-the-ramparts](https://www.wowhead.com/quest=29528/war-on-the-ramparts)

**Comment by grzewal1** [comment]
corrected, verification needed
