### ISSUE TITLE
[Quest][Borean Tundra] Hatching a Plan

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#305]
1. (Name of Quest, Spell, object etc.): Hatching a Plan
2. (ID): 11936
3. (Description): Coldarra Wyrmkins doesn't drop Frozen Axe (which should 81% drop rate) which are needed to destroy Dragon Eggs.
4. (Wowhead link): https://www.wowhead.com/quest=11936/hatching-a-plan

**Comment by grzewal1** [comment]
fixed
