### ISSUE TITLE
[Item][Borean Tundra] Winterfin Clam

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#306]
1. (Name of Quest, Spell, object etc.): **Winterfin Clam**
2. (ID): 34597
3. (Description): After you finish a quest to gather 5 of them for **Quest: Winterfin Commerce** you can't loot them from **Winterfin Clam (container)** - they're empty and they're not dropping from **Winterfin murlocs**. They're available only during quest, but they shouldn't be, because there's a Clam Vendor who sells items for them - **Ahlurglgr**.
4. (Wowhead link): https://www.wowhead.com/item=34597/winterfin-clam

Quest: Winterfin Commerce link: https://www.wowhead.com/quest=11559/winterfin-commerce
Winterfin Clam (container) link: https://www.wowhead.com/object=187367/winterfin-clam
Ahlurglgr link: https://www.wowhead.com/npc=25206/ahlurglgr

**Comment by grzewal1** [comment]
fixed
