### ISSUE TITLE
[QUEST] Bait and Switch

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#309]
1. (Name of Quest, Spell, object etc.): Bait and Switch
2. (ID): 11951
3. (Description): there are no crystalized mana shards in Coldarra
4. (Wowhead link): [https://www.wowhead.com/quest=11951/bait-and-switch](https://www.wowhead.com/quest=11951/bait-and-switch)

**Comment by grzewal1** [comment]
fixed
