### ISSUE TITLE
[Quest][Borean Tundra] Finding the Phylactery

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#313]
1. (Name of Quest, Spell, object etc.): Finding the Phylactery
2. (ID): 11956
3. (Description): Tanathal's Phylactery doesn't drop from Phylactery Guardian (drop rate is 99%)
4. (Wowhead link): https://www.wowhead.com/quest=11956/finding-the-phylactery

**Comment by grzewal1** [comment]
fixed
