### ISSUE TITLE
[QUEST] From the Mouth of Madness

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#318]
1. (Name of Quest, Spell, object etc.): From the Mouth of Madness
2. (ID): 25297
3. (Description): can't interact with stonebloom so can't pick it up
4. (Wowhead link): [https://www.wowhead.com/quest=25297/from-the-mouth-of-madness](https://www.wowhead.com/quest=25297/from-the-mouth-of-madness)

**Comment by matt155** [comment]
It's still a thing on my another character.
