### ISSUE TITLE
Resetujący się questlog

### ISSUE THREAD

**Issue by Harertz** [Blackhandpl/bugtracker#32]
Nie wiem czy to bug czy co, ale gdy np mamy quest na zabicie i zabijemy 5/10 potworów po wylogowaniu się i wejściu ponownie na postać liczba się resetuje i wtedy nie wiadomo ile mamy jeszcze zabić to samo jest z itemami które musimy dropnąć tylko, że tutaj bug jest groźniejszy bo możemy te itemy w nieskończoność zdobywać a jak są warte jakieś pieniądze po sprzedaży to można bugować sobie golda ;/

**Comment by Harcok66** [comment]
Gdy zabijesz po relogu mobka pokaże się prawidłowa ilość tak samo z quest itemami.

**Comment by Harertz** [comment]
No własnie nie ;/

**Comment by Icelandman** [comment]
u mnie tak samo jak u Herertz

**Comment by illiachenvar** [comment]
potwierdzam, dodatkowo w kilku questach zauważyłam, że po samoczynnym (nawet bez wylogowania) zresetowaniu się licznika zabicie kolejnych mobów nic nie daje, licznik zostaje na 0

**Comment by kredka852** [comment]
Potwierdzam , u mnie jest taki sam bug, po wylogowaniu i ponownym zalogowaniu liczba dalej wynosi 0
