### ISSUE TITLE
[objekt] statek w Booty Bay [Eastern Kingsdom]

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#32]
![bug statku](https://user-images.githubusercontent.com/76562416/103137661-1afc9b80-46cb-11eb-983e-ed78cc4eb3e8.png)
1. (Nazwa Questa, Spella, objektu itp.): [objekt] statek w Booty Bay 
2. (ID): faction=21
3. (Opis błędu): NPC z statku nie przemieszczają się wraz z nim 
4. (Link wowhead): https://classic.wowhead.com/faction=21/booty-bay

**Comment by Mottomi3** [comment]
rzeczywiście, npc się nie przemieszczają
