### ISSUE TITLE
[QUEST] Seeds of Their Demise

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#321]
1. (Name of Quest, Spell, object etc.): Seeds of Their Demise
2. (ID): 25408
3. (Description): wailing weeds don't leave any loot but they should drop Bileberry
4. (Wowhead link): [https://www.wowhead.com/quest=25408/seeds-of-their-demise](https://www.wowhead.com/quest=25408/seeds-of-their-demise)

**Comment by matt155** [comment]
I dropped one Bileberry of the group of like 20 of Wailing Weeds. Drop rate is 94%
