### ISSUE TITLE
[QUEST] Flight in  the Firelands

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#325]
1. (Name of Quest, Spell, object etc.): Flight in  the Firelands
2. (ID): 25523
3. (Description):  can't mount Aviana's Guardian even if i have a lance equiped
4. (Wowhead link): [https://www.wowhead.com/quest=25523/flight-in-the-firelands](https://www.wowhead.com/quest=25523/flight-in-the-firelands)

**Comment by matt155** [comment]
Still the same - cannot mount Aviana's Guardian
