### ISSUE TITLE
[QUEST] Priorities!

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#333]
1. (Name of Quest, Spell, object etc.): Priorities!
2. (ID): 31739
3. (Description): Lin Applebloom is missing
4. (Wowhead link):  [https://www.wowhead.com/quest=31739/priorities](https://www.wowhead.com/quest=31739/priorities)

**Comment by matt155** [comment]
I'm doing this quest on second character and there's no Lin Applebloom too.
