### ISSUE TITLE
The Depravity of the Forsaken

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#34]
1. The Depravity of the Forsaken(
2. 27205
3. Event się nie odpala, misja powinna być dostepna po ukończeniu https://www.wowhead.com/quest=27199/ashes-to-ashes
4. https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken

Western Plagyelands

**Comment by grzewal1** [comment]
quest zalicz co prawda no blizzlike ale jest
