### ISSUE TITLE
Eviscerate

### ISSUE THREAD

**Issue by Firegems** [Blackhandpl/bugtracker#34]
1. Eviscerate

2. 2098

3.Umiejętność nie skaluje obrażeń z levelem i nie działa prawidłowo , na wszystkich 5 combo bije 11 dmg a powinno 50 [aktualna wartość na LV  7 mojej postaci ]

4. http://www.wowhead.com/spell=2098/eviscerate

**Comment by thomas33** [comment]
Naprawione
