### ISSUE TITLE
[QUEST] [Coldarra] Nuts for Berries 

### ISSUE THREAD

**Issue by DrRostov** [Blackhandpl/bugtracker#342]
1. (Name of Quest, Spell, object etc.): Nuts for Berries
2. (ID): 11912
3. (Description): There is no Frostberries bushes anywhere in Coldarra
4. (Wowhead link): https://www.wowhead.com/quest=11912/nuts-for-berries

**Comment by matt155** [comment]
https://github.com/Blackhandpl/bugtracker/issues/304
Check if someone posted the Issue already, before posting.
