### ISSUE TITLE
ITEM LEVEL 

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#347]
1. Item lvl
2. brak
3. kalkulacja naszego item lv jest ciagle 0 nie istnotne co nosimy mamy ciagle zero co przeszkadza w pozniejszym czasie zeby random dungi/ raidy robic gdzie wymagany jest item lv
4. brak

**Comment by ravel1** [comment]
Naprawione. Itemlvl jest brany pod uwagę ale jest teraz wizualny bug, który nie pokazuje ilvl.
