### ISSUE TITLE
Val'kyr Incursion

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#35]
1. Val'kyr Incursion
2. 27201
3. NPC nam nie pomagają, valkirie do ubicia latają zbyt wysoko. 
Misja powinna być dostepna po ukonczeniu https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken
4. https://www.wowhead.com/quest=27201/valkyr-incursion

**Comment by grzewal1** [comment]
są też przy ziemi
