### ISSUE TITLE
Mottled Caterpillar

### ISSUE THREAD

**Issue by Youki1** [Blackhandpl/bugtracker#35]
1. Mottled Caterpillar
2. 59754
3. Dropi item clothowy PvP poziomu 700iLv  http://www.wowhead.com/item=126026/warmongering-combatants-amice-of-prowess&bonus=0
4. http://www.wowhead.com/npc=59754/mottled-caterpillar
link na potwierdzenie http://imgur.com/x1PaudW

**Comment by thomas33** [comment]
Naprawione
