### ISSUE TITLE
[QUEST] Lessons from the lost isles

### ISSUE THREAD

**Issue by hugyy59** [Blackhandpl/bugtracker#360]
1. (Name of Quest, Spell, object etc.): Lessons from the lost isles
2. (ID): 26003
3. (Description): Too low spawnrate, only 3 Darnassian Scouts are spawning.
4. (Wowhead link): https://www.wowhead.com/quest=26003/lessons-from-the-lost-isles

**Comment by grzewal1** [comment]
fixed
