### ISSUE TITLE
Instance:Ragefire Chasm

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#363]
1.Ragefire Chasm
2.Brak
3. Nie ma bosów w tej instancji oraz brakuje questów które można było na poczatku wejscia dostać i zrobić ale niestety nie mogę znaleść jakie to były.
4 http://www.wowhead.com/ragefire-chasm

**Comment by neyma852** [comment]
Bossy:
http://www.wowhead.com/npc=61408/adarogg
http://www.wowhead.com/npc=61412/dark-shaman-koranthal
http://www.wowhead.com/npc=61528/lava-guard-gordoth
http://www.wowhead.com/npc=61463/slagmaw

Questy
http://www.wowhead.com/npc=44216/bovaal-whitehorn
http://www.wowhead.com/npc=61724/commander-bagran
http://www.wowhead.com/npc=61823/high-sorceress-aryna
http://www.wowhead.com/npc=61716/invoker-xorenth
http://www.wowhead.com/npc=61822/si-7-field-commander-dirken
http://www.wowhead.com/npc=44217/stone-guard-kurjack
