### ISSUE TITLE
[QUEST] Bringer of the Light

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#365]
1. (Name of Quest, Spell, object etc.): Bringer of the Light
2. (ID): 44004
3. (Description): after last server restart after interacting with Velen nothing happens
4. (Wowhead link): [https://www.wowhead.com/quest=44004/bringer-of-the-light#comments](https://www.wowhead.com/quest=44004/bringer-of-the-light#comments)

**Comment by ravel1** [comment]
You have to wait for resetID (once per week).
