### ISSUE TITLE
Wandering Isle

### ISSUE THREAD

**Issue by Fatmousus** [Blackhandpl/bugtracker#38]
1. Wandering Isle
2. ID: 5736
3. Problem tkwi w tym, że po śmierci powinienem odrodzić się gdzieś na tej wyspie, a tymczasem odradza mnie w Azeroth przez co nie mogę już na tego ,,żółwia" wrócić. Tylko jak się opuści wyspę dobrowolnie po skończeniu wszystkich questów to wtedy nie można na nią powrócić.
4. http://www.wowhead.com/zone=5736/the-wandering-isle

**Comment by Harcok66** [comment]
Możesz wrócić na tą wyspe za pomocą HS.

**Comment by Fatmousus** [comment]
Z góry przepraszam, no ale kurwa no tak ! Nie pomyślałem :D
