### ISSUE TITLE
[NPC][Tanaan Jungle] Fel Rangari Anaara

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#391]
1. (Name of Quest, Spell, object etc.): Fel Rangari Anaara
2. (ID): 93229
3. (Description): This NPC is overpowered. She goes in Stealth and one shots me. She is 100lv and I'm 108lv. (I mean I think she's overpowered, I've read she was challenging for 100lv players)
4. (Wowhead link): https://www.wowhead.com/npc=93229/fel-rangari-anaara

**Comment by Mottomi3** [comment]
stats looking ok
