### ISSUE TITLE
Azsuna Npc quest giver

### ISSUE THREAD

**Issue by Samerhajj** [Blackhandpl/bugtracker#394]
1. (Name of Quest, Spell, object etc.): Going to waste
2. (ID): Tutonigeria
3. (Description): npc is not there to give quest. need the quest for the world quest kirin tor
4. (Wowhead link): https://www.wowhead.com/quest=40875/going-to-waste

**Comment by Mottomi3** [comment]
Its required q: Going Out With a Bang
Without complete it, he will be invisible
