### ISSUE TITLE
[WORLD QUEST] Bloodgazer Swarm!

### ISSUE THREAD

**Issue by Matti297** [Blackhandpl/bugtracker#396]
1. (Name of Quest, Spell, object etc.): Bloodgazer Swarm!
2. (ID): 44894
3. (Description): nothing you do gives you credit towards finishing quest
4. (Wowhead link): [https://www.wowhead.com/quest=44894/bloodgazer-swarm](https://www.wowhead.com/quest=44894/bloodgazer-swarm)

**Comment by Mottomi3** [comment]
![image](https://user-images.githubusercontent.com/16565487/118900004-49944080-b910-11eb-9b6c-1797effd3df7.png)
