### ISSUE TITLE
Learning the Ropes

### ISSUE THREAD

**Issue by illiachenvar** [Blackhandpl/bugtracker#4]
1. Learning the Ropes
2. quest=31308
3. Mamy zrobić pierwszą walkę battlepetów... ale nie ma nigdzie battlepetów
4. http://www.wowhead.com/quest=31308/learning-the-ropes

**Comment by Harcok66** [comment]
Aktualnie z tego co wiem system Battlepet nie został oskryptowany na serwerze.

**Comment by illiachenvar** [comment]
ale fajnie by było jakby jednak ruszyć ten temat... osobiście lubię walki battlepets

**Comment by Harcok66** [comment]
Też lubię i dobrze, że zgłaszasz bugi.

**Comment by thomas33** [comment]
#275
