### ISSUE TITLE
[WORLD QUEST][STORMHEIM] Direbeak Swarm!

### ISSUE THREAD

**Issue by DrRostov** [Blackhandpl/bugtracker#434]
1. (Name of Quest, Spell, object etc.): Direbeak Swarm!
2. (ID): 44893
3. (Description): This WQ is not workig. When I came to place and started killing direbeaks bar is not filling at all.
4. (Wowhead link): https://www.wowhead.com/quest=44893/direbeak-swarm

**Comment by Mottomi3** [comment]
![Uploading image.png…]()
