### ISSUE TITLE
Quest: Wanted: Kil'uun

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#443]
1-Nazwa questa - Wanted: Kil'uun
2-ID - 34103
3-Opis:Nie mogę znaleźć moba którego trzeba zabić by zdobyć item ID [112380]
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=34103/wanted-kiluun](url)

**Comment by cheester93** [comment]
Closed on jest na serverze ;p
