### ISSUE TITLE
[quest] Charge! [class] [blood elf]

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#45]
1. (Nazwa Questa, Spella, objektu itp.): [quest] Charge! [class] [blod elf]
2. (ID): quest=27091
3. (Opis błędu): brak reakcji , nie można pobrać zadania , obecnie testowane 4 różne klasy w blood elf i każda nie ma zadania klasowego 
4. (Link wowhead): https://www.wowhead.com/quest=27091/charge

**Comment by ravel1** [comment]
Quest został usunięty przez Blizzarda i na Legionie już nie wystepuje:
"This quest was marked obsolete by Blizzard and cannot be obtained or completed."
