### ISSUE TITLE
[Ancient Mana NPC][Suramar] Felbound Manasaber

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#452]
1. (Name of Quest, Spell, object etc.): Felbound Manasaber
2. (ID): 113682
3. (Description): You can't free Felbound Manasaber by giving it 50 Ancient Mana (next thing for you can't use Ancient Mana)
4. (Wowhead link): https://www.wowhead.com/npc=113682/felbound-manasaber

**Comment by Mottomi3** [comment]
Check it now
