### ISSUE TITLE
[Ancient Mana NPC][Suramar] First Arcanist Thalyssra

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#454]
1. (Name of Quest, Spell, object etc.): First Arcanist Thalyssra
2. (ID): 97140
3. (Description): You can't spend Ancient Mana at her for Feed her (unless it's Daily Quest), you can't spend Ancient Mana to help withered with combat training and you can't spend Ancient Mana to Gain Ward of the First Arcanist.
4. (Wowhead link): https://www.wowhead.com/npc=97140/first-arcanist-thalyssra

**Comment by matt155** [comment]
Combat Training started to work After fulfill Nightfallen But Not Forgotten achievemet all Storylines. I've got Scenario after got World Quest for that.

**Comment by Mottomi3** [comment]
some fixes, need info about enter instance option
