### ISSUE TITLE
WoW application : Okno WoWa

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#456]
opis problemu : Po kliknięciu klawisza Esc nie wyskakuje okno Game Menu .
opis problemu : Gdy mamy włączoną mapę nie możemy jej wyłączyć klawiszem Esc .
opis problemu : Nie zbiera nam dropu z wszystkich mobów na raz które zabiliśmy .
opis problemu : Po zakończeniu questa i rozmowie z NPC nie zamyka nam się okno z rozmowy i nie można zamknąć go klawiszem Esc.
opis problemu: wszystkie przerzutnie (w action bar od okna postaci) nie da się zamknąć klawiszem Esc

**Comment by cheester93** [comment]
jesli chodzi o mass loot mobkow to tak ale jesli chodzi o klawisz esc u mnie wszystko gra ;p

**Comment by Vikingson** [comment]
u mnie nie :/ może addony coś gryzą ale wątpię w to

**Comment by Vikingson** [comment]
już wiem czemu , jak miałem dodatek panelu WoD to nie działał mi Esc a teraz działa jak mam dodatek legion , Ravel mi pomógł

**Comment by ravel1** [comment]
Mass loot jest już zrobiony, będzie udostępniony podczas otwarcia serwera ;)
