### ISSUE TITLE
[Skinning World Quest][Highmountain] Felhide

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#460]
1. (Name of Quest, Spell, object etc.): Felhide
2. (ID): 41561
3. (Description): Missing Target, should be around NPC Tenpak Flametotem (his camp) his ID: 97203
4. (Wowhead link): https://www.wowhead.com/quest=41561/felhide

**Comment by Mottomi3** [comment]
To check out with quest

**Comment by matt155** [comment]
WQ in this location doesn't show on quest list (doesn't assisgn to player) and it's not completing.
