### ISSUE TITLE
Twilight-Highlands ZONE

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#468]
1. Twilight-Highlands
2. brak
3. pustostan niema npc mobkow nic jedyne miejsce co istnieja jest malutka wysepka startowa  HighBank
4. http://www.wowhead.com/twilight-highlands

**Comment by thomas33** [comment]
#205

**Comment by cheester93** [comment]
tak tylko tam opisal ze niema wogole
a sa na poczatku na statku i npc i mobki wiec wstalilem nowy bo nie bylo tak jak opisal na prawde
