### ISSUE TITLE
[NPC][Azsuna] Lytheron Gloomscale, Marsh Hydra

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#471]
1. (Name of Quest, Spell, object etc.): Lytheron Gloomscale, Marsh Hydra
2. (ID): 111383, 112861
3. (Description): Those NPCs at Alluvanon's Delta are not attacking at all. If you walk by them they don't attack and they don't attack when they're attacked.
4. (Wowhead link): https://www.wowhead.com/npc=111383/lytheron-gloomscale
https://www.wowhead.com/npc=112861/marsh-hydra

**Comment by Mottomi3** [comment]
To check
