### ISSUE TITLE
Quest: Take Him to the Earthcaller

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#479]
1-Nazwa questa - Take Him to the Earthcaller
2-ID - 26413
3-Opis:Po wstąpieniu na daną lokalizacje nie zalicza nam questa 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26413/take-him-to-the-earthcaller](url)

**Comment by grzewal1** [comment]
"dziwnie" zrobiony quest ale działa
