### ISSUE TITLE
[QUEST] The Traitor's Destruction [ghostland]

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#48]
1. (Nazwa Questa, Spella, objektu itp.): [QUEST] The Traitor's Destruction [ghostland]
2. (ID): quest=9167
3. (Opis błędu): Brak zadania u NPC 
4. (Link wowhead): https://www.wowhead.com/quest=9167/the-traitors-destruction

**Comment by grzewal1** [comment]
dostajemy misję u npc'a
