### ISSUE TITLE
Quest: One With the Ground

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#487]
1-Nazwa questa - One With the Ground
2-ID - 27934
3-Opis:Nie działa , można przyjąć zadanie ale nie można go wykonać ( rozmowa z npc by nas przemienił )
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=27934/one-with-the-ground](url)

**Comment by grzewal1** [comment]
zalicza, ale nie tak jak na globie
