### ISSUE TITLE
[QUEST] The Twin Ziggurats [GHOSTLAND]

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#49]
1. (Nazwa Questa, Spella, objektu itp.): [QUEST] The Twin Ziggurats [GHOSTLAND]
2. (ID): quest=9176
3. (Opis błędu): Brak zadania u NPC 
4. (Link wowhead): https://www.wowhead.com/quest=9176/the-twin-ziggurats

**Comment by ravel1** [comment]
Jest to część chaina i quest można u niego dostać.
