### ISSUE TITLE
[Quest] [Suramar] Trail of Echoes

### ISSUE THREAD

**Issue by Shredz89** [Blackhandpl/bugtracker#493]
1. (Name of Quest, Spell, object etc.): Trail of Echoes
2. (ID):  39987
3. (Description): Last part of the quest, finding arcanyst thalyssra, does not trigger/complete.
4. (Wowhead link): https://www.wowhead.com/quest=39987/trail-of-echoes

**Comment by matt155** [comment]
I'm doing on second character and I confirm that. 
On my first character It was complete-able, but when she walked she wasn't there just her bubble. I guess you were repairing and we got some another bug. (I issued that, but it's not there anymore - in opened or closed issues). And she got wrong appearence. She should be dessicated from lack of Mana.

**Comment by matt155** [comment]
I'm redoing that quest and still not working. Still doesn't trigger "First Arcanist Thalyssra found" objective.
