### ISSUE TITLE
[NPC][Isle of Thunder] Nalak <The Storm Lord>

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#494]
1. (Name of Quest, Spell, object etc.): Nalak <The Storm Lord>
2. (ID): 69099
3. (Description): It's second time I see Nalak is bugged to the floor and it's impossible to attack him. Yesterday i killed him normally. I think sometimes he spawns wrong.
4. (Wowhead link): https://www.wowhead.com/npc=/nalak

**Comment by Mottomi3** [comment]
This is ok
https://www.wowhead.com/npc=69099/nalak
