### ISSUE TITLE
Quest: Sealing the Way

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#498]
1-Nazwa questa - Sealing the Way
2-ID - 26501
3-Opis: nie działa quest item który trzeba użyć na celu i także nie jest możliwe zakończenie questa przez komendę więc jeśli są jakieś inne questy po tym to nie mogłem ich sprawdzić 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26501/sealing-the-way](url)

**Comment by grzewal1** [comment]
Zrobiony obejściowo
