### ISSUE TITLE
Skill - Fishing

### ISSUE THREAD

**Issue by illiachenvar** [Blackhandpl/bugtracker#5]
1. Fishing
2. skill=356
3. Można co prawda kupić wędkę, ale łowić już nie - zero reakcji przy próbie użycia wędki
4. http://www.wowhead.com/skill=356/fishing

**Comment by Harcok66** [comment]
Ten problem jest już od dawna znany.

**Comment by illiachenvar** [comment]
tak...faktycznie, to oświeć mnie po co jest nowy bugtracker?

**Comment by Harcok66** [comment]
Przecież nie powiedziałem żebyś nie zgłaszał tego bugu tylko że jest już znany, o co Ci chodzi ?

**Comment by illiachenvar** [comment]
mi o bugi a Tobie?

**Comment by thomas33** [comment]
fixed
