### ISSUE TITLE
[QUEST] Hero of the Sin'dorei [GHOSTLAND ]

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#50]
1. (Nazwa Questa, Spella, objektu itp.): [QUEST] Hero of the Sin'dorei [GHOSTLAND ]
2. (ID): quest=9328
3. (Opis błędu): Brak zadania u NPC 
4. (Link wowhead): https://www.wowhead.com/quest=9328/hero-of-the-sindorei

**Comment by ravel1** [comment]
Żeby otrzymać tego questa trzeba być Blood Elfem oraz trzeba ukończyć quest The Traitor's Destruction.
