### ISSUE TITLE
Quest: Close Escort

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#502]
1-Nazwa questa - Close Escort
2-ID - 26632
3-Opis: Nie można porozmawiać z NPC by przywołał maszynę którą trzeba eskortować
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26632/close-escort](url)

**Comment by grzewal1** [comment]
Wystarczy zabić mobka i quest zaliczony
