### ISSUE TITLE
Quest: Keep Them off the Front

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#503]
1-Nazwa questa - Keep Them off the Front
2-ID - 26755
3-Opis:Nie mogę wskoczyć na katapulte by zabić moby i wykonać zadanie 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26755/keep-them-off-the-front](url)

**Comment by grzewal1** [comment]
można zabić bez katapulty
