### ISSUE TITLE
Quest: Reactivate the Constructs

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#504]
1-Nazwa questa - Reactivate the Constructs
2-ID - 26762
3-Opis:nie moge wykonać questa. problem tkwi w tym że nie mogę chyba zniszczyć czy tam porozmawiać z 5 xNPC w wskazanej lokalizacji.
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26762/reactivate-the-constructs](url)

**Comment by grzewal1** [comment]
automatycznie się akceptuje wykonanie
