### ISSUE TITLE
Quest: Sprout No More

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#506]
1-Nazwa questa - Sprout No More
2-ID - 26791
3-Opis: Nie mogę wykonać 1 zadania( przywołanie  golema i nie mogę kliknąć na golema) i chyba także nie działa 2 wymaganie z zadanie , znalezieniu i kliknięciu na 5 grzybów
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26791/sprout-no-more](url)

**Comment by grzewal1** [comment]
grzyby trzeba zabić
