### ISSUE TITLE
Quest: On Even Ground

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#515]
1-Nazwa questa - On Even Ground
2-ID - 26314
3-Opis:Nie mogę użyć quest item'a na NPC by wykonać zadanie 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26314/on-even-ground](url)

**Comment by grzewal1** [comment]
spell=79688 nie działa ale można je normalnie zabić
