### ISSUE TITLE
NPC: Stormcaller Mylra

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#518]
1-Nazwa NPC - Stormcaller Mylra
2-ID - 42684
3-Opis: Ten NPC i inni z jego otoczenia są w złym miejscu . Ich miejsce jest na zeppelinie a spadli z niego i są na ziemi 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/npc=42684/stormcaller-mylra](url) 
linki niżej do innych npc którzy spadli
2 [http://www.wowhead.com/npc=53738/aggra](url)
3 [http://www.wowhead.com/npc=43082/first-mate-moody](url)
4 [http://www.wowhead.com/npc=43346/twilight-saboteur](url) x10 

Chyba to wszyscy

**Comment by grzewal1** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1942
