### ISSUE TITLE
[Client][Okno wyboru postaci] Panel wyboru klasy i rasy

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#52]
1. (Nazwa Questa, Spella, objektu itp.): [Client][Okno wyboru postaci] Panel wyboru klasy i rasy WYMAGA TESTU 
2. (ID): brak . Client
3. (Opis błędu): Brak możliwości przewijania tekstu w tabeli informacji , wydaje mi się że jest tam wiecej treści która jest zablokowana 
![brak możliwosci przewijania](https://user-images.githubusercontent.com/76562416/103142270-af352580-4700-11eb-800b-ceca60eb6605.png)

4. (Link wowhead): Brak , załączone zdjecia

**Comment by ravel1** [comment]
Paski są na szaro ponieważ nie ma więcej tekstu. U goblina jest więcej i działa. Sprawdzone również na globie.
