### ISSUE TITLE
[NPC][Stormheim] Skeletons at Field of Fallen Kings

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#520]
1. (Name of Quest, Spell, object etc.): Skeletons at Field of Fallen Kings
2. (ID): -
3. (Description): There's skeletons I can't click on them, they're attacking and I can't. Is it normal? I don't know the name because It's not showing.
4. (Wowhead link): -

**Comment by Mottomi3** [comment]
Where it is ?
