### ISSUE TITLE
Quest: Violent Gale

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#523]
1-Nazwa questa - Violent Gale
2-ID - 26426
3-Opis: Nie załącza mi wykonanego questu podczas odwiedzenia wskazanej lokalizacji 
Testowane na [MAG bloodelf]
4-link wowhead: [http://www.wowhead.com/quest=26426/violent-gale](url)

**Comment by grzewal1** [comment]
wystarczy kliknąć npc
