### ISSUE TITLE
Quest: Elemental Bonds: Patience

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#535]
1-Nazwa questa - Elemental Bonds: Patience
2-ID - 29329
3-Opis:Brak możliwości porozmawiania z npc od którego mamy misje by nas przemienił i byśmy wykonali zadanie 
Testowane na [MAG bloodelf]
4-link wowhead: [ http://www.wowhead.com/quest=29329/elemental-bonds-patience ](url)

**Comment by grzewal1** [comment]
Quest zalicza, ale nie bizzlike
