### ISSUE TITLE
NPC: Stormcaller Mylra

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#538]
1-Nazwa NPC - Stormcaller Mylra
2-ID - 42684
3-Opis:Mam nad tym NPC znak zapytania (żółty oczywiście) ale nie mogę z tym NPC porozmawiać i nic zrobić . jeśli są u niego jakieś zadania nie jestem w stanie ich sprawdzić 
PS. po chwili ten znak zapytania zmienił się na żółty wykrzyknik i także nie mogę z nim porozmawiać itp
Testowane na [MAG bloodelf]
4-link wowhead: [ http://www.wowhead.com/npc=42684/stormcaller-mylra ](url)

**Comment by grzewal1** [comment]
https://github.com/Blackhandpl/bugtracker/issues/1942
