### ISSUE TITLE
[NPC][Azsuna] Warden Trainee

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#550]
1. (Name of Quest, Spell, object etc.): Warden Trainee
2. (ID): 102057, 111625, 111757
3. (Description): Warden Trainees are floating or levitating. I don't know which ID is it, but there's a lot of them at Warden's Redoubt and 2 at Watchers' Aerie.
4. (Wowhead link): https://www.wowhead.com/npc=102057/warden-trainee
https://www.wowhead.com/npc=111625/warden-trainee
https://www.wowhead.com/npc=111757/warden-trainee

**Comment by Mottomi3** [comment]
spell to write, rest is fixed
