### ISSUE TITLE
Spell: Ice Barrier

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#577]
1-Nazwa Umiejętności(spell) - Ice Barrier
2-ID - 11426
3-Opis: Po włączeniu w Spellbook informacja o spellu jest inna niż załączona moc która zostaje nam dana 
Testowane na [MAG bloodelf fire]
4-link wowhead: [  http://www.wowhead.com/spell=11426/ice-barrier   ](url)

**Comment by Gieniek** [comment]
Podtwierdzone info. Daje połowe mniej osłony niz powinno.

**Comment by ravel1** [comment]
Naprawione, teraz jest liczony absorb z tego wzroru: [0 + Spell power * 10 * 1 * (1 + Versatility)] damage
