### ISSUE TITLE
atakujacy martwy mob

### ISSUE THREAD

**Issue by kmieciu001** [Blackhandpl/bugtracker#584]
Mulgore - czasami agresywne moby nadal atakują po zabiciu.

**Comment by matt155** [comment]
Podaj przykłady, chłopaki co działają nad tym nie będą sprawdzać każdego moba w Mulgore, gdy mają co innego bardziej sprecyzowanego ;) Najlepiej linka z wowhead. Tzn też wydaje mi się że może nie ma tam aż tak dużo różnych mobów, no ale tak na przyszłość. Zobacz sobie jak inne zgłoszenia wyglądają.
