### ISSUE TITLE
Spell: Slow

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#589]
1-Nazwa Umiejętności(spell) - Slow
2-ID - 31589
3-Opis: W spellbok informacja odnośnie tej umiejętności to Reduces the target's movement speed by 52% for 15.3 sec. A na celu jest pokazane że 50% ma tylko 

Testowane na [MAG bloodelf FROST]
4-link wowhead: [   http://www.wowhead.com/spell=31589/slow  ](url)

**Comment by ravel1** [comment]
Visualbug, powinno spowalniać tylko o 50%.
