### ISSUE TITLE
[Deadkhnel][NPC] Darnell 

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#59]
1. (Nazwa Questa, Spella, objektu itp.): [Deadkhnel][NPC] Darnell 
2. (ID): npc=49425
3. (Opis błędu): Brak NPC na swoim stanowisku u którego oddaje się misje  
4. (Link wowhead): https://www.wowhead.com/npc=49425/darnell

**Comment by Vikingson125** [comment]
NPC jest do misji https://www.wowhead.com/quest=24970/no-better-than-the-zombies

**Comment by Mottomi3** [comment]
Darnell nie pokazuje się po wzięciu questa.
Możliwe że jego skrypt miał bugi na globie.
Sprawdzić, czy pojawi się po wzięciu i opuszczeniu lokacji i powrocie do niej
