### ISSUE TITLE
Never Trust a Big Barb and a Smile

### ISSUE THREAD

**Issue by mario12pl** [Blackhandpl/bugtracker#6]
1. Never Trust a Big Barb and a Smile
2. ID: 25165
3. Nie działający Poison Extraction Totem postawiony blisko Clattering Scorpid nie zbiera jego trucizny.
4. http://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile

**Comment by Harertz** [comment]
Ten bug podobno został naprawiony.

**Comment by Icelandman** [comment]
nie dziala
