### ISSUE TITLE
[deadkhnel][quest] Trail-Worn Scroll 

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#60]
1. (Nazwa Questa, Spella, objektu itp.): [deadkhnel][quest] Trail-Worn Scroll 
2. (ID): quest=24962
3. (Opis błędu): nie można oddać misji 
4. (Link wowhead): https://www.wowhead.com/quest=24962/trail-worn-scroll

**Comment by ravel1** [comment]
"This quest was marked obsolete by Blizzard and cannot be obtained or completed."

Quest usunięty.
