### ISSUE TITLE
[deadkhnell][quest] Assault on the Rotbrain Encampment

### ISSUE THREAD

**Issue by Vikingson125** [Blackhandpl/bugtracker#61]
1. (Nazwa Questa, Spella, objektu itp.): [deadkhnell][quest] Assault on the Rotbrain Encampment
2. (ID): quest=24971
3. (Opis błędu): Brak NPC u którego można podjąć się misji , misja do przetestowania 
4. (Link wowhead): https://www.wowhead.com/quest=24971/assault-on-the-rotbrain-encampment

**Comment by Mottomi3** [comment]
Problem z npc
https://www.wowhead.com/npc=49425/darnell
