### ISSUE TITLE
[NPC][Borean Tundra] Gargoyles in Naxxanar

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#612]
1. (Name of Quest, Spell, object etc.): Gargoyles in Naxxanar
2. (ID): -
3. (Description): There's some Gargoyles in Naxxanar which attacks a player, but you can't target them and attack them back. And I think they are lack of animation. Like a statue just flying.
4. (Wowhead link): -

**Comment by matt155** [comment]
Those are at Temple City of En'kilah too.

**Comment by Mottomi3** [comment]
some fixes
Still no fly anim
