### ISSUE TITLE
razorfen-kraul INSTANCE

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#624]
1. razorfen-kraul
2. brak
3. brak npc z questami oraz brakuje bossa npc=4425/blind-hunter
4. http://www.wowhead.com/razorfen-kraul

**Comment by neyma852** [comment]
http://www.wowhead.com/npc=44415/spirit-of-agamaggan
http://www.wowhead.com/npc=44402/auld-stonespire
