### ISSUE TITLE
[NPC][Netherlight Temple] Acolyte

### ISSUE THREAD

**Issue by matt155** [Blackhandpl/bugtracker#631]
1. (Name of Quest, Spell, object etc.): Acolyte
2. (ID): 113510
3. (Description): Near Grand Challenger's Bounty chest should stand Acolyte. There's only exclamation mark and scroll in air which moves a little. On map i have exclamation mark, when I put my cursor on that i have "Netherlight Temple Acolyte". I don't know if I'm not supposed to access this quest at the moment, but it looks weird.
4. (Wowhead link): https://www.wowhead.com/npc=113510/acolyte

**Comment by Mottomi3** [comment]
To check
