### ISSUE TITLE
Quest: A Refugee's Quandary

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#632]
1-Nazwa questa - A Refugee's Quandary
2-ID - 3361
3-Opis: Brak możliwości zdobycia quest item'u
Testowane na [  priest   ]
4-link wowhead: [ http://www.wowhead.com/quest=3361/a-refugees-quandary ](url)

**Comment by Grzegorzdut** [comment]
Warrior ma ten sam błąd.

**Comment by thomas33** [comment]
#738
