### ISSUE TITLE
Quest: First Things First: We're Gonna Need Some Beer

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#634]
1-Nazwa questa - First Things First: We're Gonna Need Some Beer
2-ID - 24474
3-Opis:Brak możliwości zdobycia quest itemu . da rade klikać na lokalizacje gdzie quest item ma być ale w oknie go nie ma 
Testowane na [  priest   ]
4-link wowhead: [http://www.wowhead.com/quest=24474/first-things-first-were-gonna-need-some-beer  ](url)

**Comment by Grzegorzdut** [comment]
Warrior ma to samo.
