### ISSUE TITLE
NPC:Frostmane Scavenger

### ISSUE THREAD

**Issue by Vikingson** [Blackhandpl/bugtracker#644]
1:ID :41146
2:Aktualne działanie:Rzuca kostką rubika dosłownie biało czarną wraz z jego sąsiadem o ID [41251] 
3:Oczekiwane działanie:jakaś inna grafika spella
4:Kroki prowadzące do odtworzenia problemu:podejście do NPC [41146] lub zaatakowanie npc[41251]
5:Wowhead Link: [ http://www.wowhead.com/npc=41146/frostmane-scavenger ](url)
2-[http://www.wowhead.com/npc=41251/frostmane-builder](url)

**Comment by grzewal1** [comment]
Rzuca młotkiem
