### ISSUE TITLE
Spirit Healer

### ISSUE THREAD

**Issue by hipolit** [Blackhandpl/bugtracker#65]
1) Spirit Healer

2) ID: 32537

3) Gdy się zginie brak NPC do wskrzeszania w całym Northern Barrens (ID: 17). W Mulgore (ID : 215) też nie było.

4) http://www.wowhead.com/npc=32537/spirit-healer

**Comment by Icelandman** [comment]
Dodaje w dutarze rowniez nie ma pewnie nigdziej ich nie ma

**Comment by thomas33** [comment]
**Naprawione.**
