### ISSUE TITLE
Pandaria Mobs 

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#655]
1. Mobki w pandari
2. -
3. damage mobkow w pandari jest troche zbyt mocny przy 1vs1 mobka jest czesto  walka kto pierwszy ten lepszy ....
4. -

**Comment by ravel1** [comment]
DMG, jest taki jak na globie - osobiście sprawdzałem.

**Comment by cheester93** [comment]
to może tkwi nasz damage ze mamy pare lv większy od normal mobka i ledwo go zabijamy tak jak opisałem kto pierwszy ten lepszy
