### ISSUE TITLE
Pet Specialization

### ISSUE THREAD

**Issue by illiachenvar** [Blackhandpl/bugtracker#7]
1. Pet Specializations
2. brak
3. W panelu Specialization & Talents (N) nie można wybrać żadnej z trzech specjalizacji dla peta. A dokładniej - wybór nie zostaje zapisany. 
4. http://www.wowhead.com/guide=3337/hunter-pet-resource-guide#pet-specializations

**Comment by thomas33** [comment]
Naprawione.
