### ISSUE TITLE
Quest: Ghoulish Effigy

### ISSUE THREAD

**Issue by pularys** [Blackhandpl/bugtracker#708]
Po wydropieniu 2 Ghoul Rib nie da sie podnieść kolejnych. Dostajemy info `Already Looted`
Id: 26677, Item Id: 884
Wowhead link: http://www.wowhead.com/quest=26677/ghoulish-effigy

**Comment by Sza65** [comment]
Teraz juz nawet pierwszego nie mozna podniesc - already loted

**Comment by ravel1** [comment]
#738
