### ISSUE TITLE
Quest: Army of the Black Dragon

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#714]
1.Army of the Black Dragon
2. 1168
3. Mobki biegaja z czaszkami i maja po 20k hp nie da sie ich zabijac
4. http://www.wowhead.com/quest=1168/army-of-the-black-dragon

**Comment by ravel1** [comment]
Problem jest z mobkami a nie z Questem... Zgłaszaj to poprawnie bo to już któreś takie zgłoszenie z rzędu...
