### ISSUE TITLE
master-hwang NPC

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#740]
1. master-hwang
2. 66356
3. ten npc posiada bronie ktore powinny miec swoj wymagany lvl 80 ,90 a nie ma bronie mozna kupic za golda i nosic na kazdym lv
4. http://www.wowhead.com/npc=66356/master-hwang

**Comment by ravel1** [comment]
Zanim coś zgłosisz upewnij się, że wiesz jak to powinno działać... Wszystko jest tak jak być powinno.

**Comment by cheester93** [comment]
dziwne ze 450 item lv bronie mozna od 1 lv nosic ;/ postaram sie to sprawdzic na globalu
