### ISSUE TITLE
Caer Darrow 

### ISSUE THREAD

**Issue by Mottomi3** [Blackhandpl/bugtracker#75]
1. Lokacja do uzupełnienia w NPC
https://www.wowhead.com/npc=11281/caer-darrow-horseman
https://www.wowhead.com/npc=11279/caer-darrow-guardsman
https://www.wowhead.com/npc=11277/caer-darrow-citizen

Problem z tymi NPC jest taki, że ich nie widać bez gm mode.

Western Plaguelands

**Comment by grzewal1** [comment]
dodano npc. Aby ich zobaczyć należy mieć item https://www.wowhead.com/item=13544/spectral-essence
