### ISSUE TITLE
 [A Dumpy Job] QUEST

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#751]
1.  [A Dumpy Job]
2. 25726
3. nie idzie podniesz quest item z mobka item=55234/dumpy-level pisze already looted (-692447784/1932523280)
4. http://www.wowhead.com/quest=25726/a-dumpy-job

**Comment by ravel1** [comment]
#738

**Comment by cheester93** [comment]
sry wpisywałem w search nazwe questa nie ukazalo mi się to wiec wstawiłem..
