### ISSUE TITLE
Quest items, 2 examples, propably a lot more of these

### ISSUE THREAD

**Issue by Duannes** [Blackhandpl/bugtracker#752]
![snap 2017-01-11 at 18 09 22](https://cloud.githubusercontent.com/assets/25061932/21858596/003a362c-d82a-11e6-9dd7-7c1a75ab489b.png)

![snap 2017-01-11 at 18 10 34](https://cloud.githubusercontent.com/assets/25061932/21858603/06330fcc-d82a-11e6-842b-4a2d216868d2.png)

**Comment by ravel1** [comment]
#738
