### ISSUE TITLE
Quest Control Sample

### ISSUE THREAD

**Issue by Sza65** [Blackhandpl/bugtracker#756]
Description: Problem z lotowaniem q itemka
Current behaviour: Podczas proby podjecia questowego lotu z zabitego mobka pojawia sie napis "already looted" 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=26733/control-sample    - quest
itek: http://www.wowhead.com/item=60213/crystal-spine-basilisk-blood

**Comment by ravel1** [comment]
#738
