### ISSUE TITLE
ZONE Feralas mob

### ISSUE THREAD

**Issue by Sza65** [Blackhandpl/bugtracker#762]
Description:  w poblizu Tower of Estulan biega sobie krolik (rabbit) z czacha, jak uzre to kaplica :D
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link:

**Comment by ravel1** [comment]
Mogę się tylko domyślać o jakiego chodzi bo nie podałeś dokładnej nazwy i ID...
