### ISSUE TITLE
Incancja NPC: Razorfen Kraul

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#782]
1. Instance Razorfen Kraul
2. 
3. NPC z czaszka ID 4514,4516
4.http://www.wowhead.com/npc=4514/raging-agamar
http://www.wowhead.com/npc=4516/deaths-head-adept

**Comment by kredka852** [comment]
http://www.wowhead.com/npc=44402/auld-stonespire
http://www.wowhead.com/npc=44415/spirit-of-agamaggan

**Comment by neyma852** [comment]
http://www.wowhead.com/npc=44402/auld-stonespire
http://www.wowhead.com/npc=44415/spirit-of-agamaggan
