### ISSUE TITLE
 [Those That Couldn't Let Go] QUEST

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#820]
1.  [Those That Couldn't Let Go]
2. 27168
3. uzycie item questa dziala prawidlowo ale nie zalicza nam questa item=60861/holy-thurible byc moze wina tkwi w mobkach npc=45166/withdrawn-soul
4. http://www.wowhead.com/quest=27168/those-that-couldnt-let-go

**Comment by thomas33** [comment]
#802
