### ISSUE TITLE
OGOLNY DAMAGE CLASS

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#833]
1. damage class
2. brak
3. porownywalem 2 rzeczy a wiec damage na bh ktory zadawalem 91 warriorem w instancji byl w granicach od 800 do 4k dmg i mobki bily od 30-100 oraz na pandari na tych samych mobkach lv 87 bilem podobnie co stwarzalo walke kto szybciej zabije  bily mnie nawet do 4k dmg a teraz warrior 93 lv w instancji granice dmg 30k-280k mobki same missy a mobki 87 w pandari otrzymywaly odemnie w granicach 1-13k dmg a one od dodge do 980 dmg wydaje mi sie ze to globalny bug bo kazdy zali sie na takie walki z mobkami slabszymi jak i o tym samym lv
4. brak

**Comment by cheester93** [comment]
Warrior 93Lv GLOBAL ID MOBKA :82308 
otrzymywany dmg
Shadowmoon Stalker melee hit 1358 physical
Shadowmoon Stalker Ferocious Bite hit 3014 physical
Shadowmoon Stalker melee hit 1756 physical
Shadowmoon Stalker melee hit 1725 physical
Shadowmoon Stalker melee hit 1974 physical
Shadowmoon Stalker Ferocious Bite hit 3585 physical
Shadowmoon Stalker melee hit 1741 physical
Shadowmoon Stalker melee hit 1674 physical
Shadowmoon Stalker melee hit 1432 physical
Shadowmoon Stalker melee hit 1562 physical
Shadowmoon Stalker melee hit 1583 physical
Shadowmoon Stalker melee hit 1601 physical
Shadowmoon Stalker Ferocious Bite hit 3065 physical (183 overkill)

**Comment by cheester93** [comment]
Warrior 93Lv GLOBAL ID MOBKA :82308
zadawany dmg
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 378 Physical
melee hit Shadowmoon Stalker 378 Physical
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 378 Physical
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 378 Physical
melee hit Shadowmoon Stalker 377 Physical
melee hit Shadowmoon Stalker 378 Physical
melee hit Shadowmoon Stalker 378 Physical

**Comment by cheester93** [comment]
Warrior 93Lv GLOBAL ID MOBKA :46382
Otrzymywany dmg
czekalem 20 udezen mobka same Miss'y
Zadawany dmg :
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 21748 Overkill)(Critical)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10706 Overkill)
melee hit Petty Criminal 336 Physical ( 10707 Overkill)
melee hit Petty Criminal 336 Physical ( 21749 Overkill)(Critical)
melee hit Petty Criminal 336 Physical ( 10707 Overkill)
melee hit Petty Criminal 336 Physical ( 21749 Overkill)(Critical)

**Comment by ravel1** [comment]
#870 
#869

**Comment by cheester93** [comment]
Moonstalker Sire 17 lv ID 2237 vs Hunter Survival 20 lv(Worgen)
melee hit Moonstalker sire 22 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 22 Physical
melee hit Moonstalker sire 22 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical

**Comment by cheester93** [comment]
Moonstalker Sire 18 lv ID 2237 vs Hunter Survival 20 lv(Worgen)
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical
melee hit Moonstalker sire 21 Physical

**Comment by cheester93** [comment]
Moonstalker Matriarch 19 lv ID 2071 vs Hunter Survival 20 lv(Worgen)
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical 
melee hit Moonstalker Matriarch 21 Physical

**Comment by cheester93** [comment]
Encrusted Tide Crawler lv 20 ID 2233 vs Hunter Survival 20lv (Worgen)
melee hit Encrusted Tide Crawler 36 physical (Critical)
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 37 physical (Critical)
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical
melee hit Encrusted Tide Crawler 18 physical

**Comment by cheester93** [comment]
Thistlefur Warrior lv 21 ID 33390 vs Hunter Survival 20lv (Worgen)
melee hit Thistlefur Warrior 20 physical
melee hit Thistlefur Warrior 21 physical
melee hit Thistlefur Warrior 21 physical
melee hit Thistlefur Warrior 20 physical
melee hit Thistlefur Warrior 42 physical (Critical)
melee hit Thistlefur Warrior 20 physical
melee hit Thistlefur Warrior 21 physical
melee hit Thistlefur Warrior 20 physical
melee hit Thistlefur Warrior 21 physical
melee hit Thistlefur Warrior 20 physical

**Comment by cheester93** [comment]
Thistlefur Shaman lv 22 ID 3924 vs Hunter Survival 20lv (Worgen)
melee hit Thistlefur Shaman 21 physical
melee hit Thistlefur Shaman 20 physical
melee hit Thistlefur Shaman 20 physical
melee hit Thistlefur Shaman 21 physical
melee hit Thistlefur Shaman 20 physical
melee hit Thistlefur Shaman 20 physical
melee hit Thistlefur Shaman 20  physical
melee hit Thistlefur Shaman 43 physical (Critical)
melee hit Thistlefur Shaman 20 physical
melee hit Thistlefur Shaman 21 physical

**Comment by cheester93** [comment]
Foulweald Totemic lv 23 ID 3750 vs Hunter Survival 20lv (Worgen)
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 21 Physical
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 21 Physical
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 20 Physical
melee hit Foulweald Totemic 21 Physical
melee hit Foulweald Totemic 40 Physical (Critical)
