### ISSUE TITLE
An Ambitious Plan

### ISSUE THREAD

**Issue by DjRai09** [Blackhandpl/bugtracker#840]
ID:9383
Z moba " Rogue Voidwalker " wypada quest item " Glowing Sanctified Cryslat "  lecz nie można go podnieść, wyskakuje następujący komunikat " Already Looted " i nic się nie dzieje nawet  po wielu prubach i po relogu tak samo.
Moim zdaniem quest itema powinno się normal;nie podnieść z moba 
http://www.wowhead.com/quest=9383/an-ambitious-plan

**Comment by ravel1** [comment]
#738
