### ISSUE TITLE
Raging Colossus

### ISSUE THREAD

**Issue by DjRai09** [Blackhandpl/bugtracker#841]
item ID:29476 

mob ID: 19188

Z moba " Raging Colossus " dropi item " Crimson Crystal Shard "  który rozpoczyna questa, nie darady podnieść tego ita  wyskakuje komunikat " Alresdy Looted"  i nic się nie dzieje

link do ita z questem- http://www.wowhead.com/item=29476/crimson-crystal-shard

link do moba z krorego leci item - http://www.wowhead.com/npc=19188/raging-colossus

**Comment by thomas33** [comment]
#738
