### ISSUE TITLE
Quest: Hatecrest Forces

### ISSUE THREAD

**Issue by Sza65** [Blackhandpl/bugtracker#843]
Description: Brak questowych mobow.
Current behaviour: Brak mobkow, a przed update serwa byly - zaczalem robic q, potem update i mobkow zero
Expected behaviour: 
Steps to reproduce the problem: 
Wowhead link: http://www.wowhead.com/quest=25399/hatecrest-forces

**Comment by ravel1** [comment]
Mobki były, ale był to dość poważny globalny problem (znacznie więcej mobów miało tego samego buga), który udało się naprawić przy okazji tego zgłoszenia ;)
