### ISSUE TITLE
Wioska: Swamprat Post

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#860]
1.Swamprat Post w Zangarmarsh, Grasuja tam Gargulce 70 lvl i odradzają się jeden po drugim. Nie da się wziać z tej wioski questów.

**Comment by ravel1** [comment]
W jakiej frakcji tam byłeś?

**Comment by ravel1** [comment]
Wioska jest hordy, stąd ochrona zabijająca ally.

**Comment by Gieniek** [comment]
Taj tylko że ja gram w Hordzie.
