### ISSUE TITLE
Wioska: Zabra"jin w Zangarmarsh

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#861]
1. Wioska Zabra"jin w Zangarmarsh szaleja w niej gargulce które bardzo szybko zabiaja

**Comment by ravel1** [comment]
W jakiej frakcji byłeś tam?

**Comment by ravel1** [comment]
Wioska jest hordy, stąd ochrona zabijająca ally.

**Comment by Gieniek** [comment]
Tylko że ja gram w Hordzie i zabijaja horde....
