### ISSUE TITLE
Quest:  [Gold Dust Exchange]

### ISSUE THREAD

**Issue by Requz** [Blackhandpl/bugtracker#867]
Description:  [Gold Dust Exchange]
Current behaviour: 
Expected behaviour: 
Steps to reproduce the problem: Przy podniesieniu 8 przedmiotów [Gold Dust] brak możliwości ukończenia questa, ponieważ potrzeba nam ich 10. Problem przedstawiony na zdjeciu. http://screenshooter.net/103035560/nffajin
Wowhead link:

**Comment by ravel1** [comment]
#738
