### ISSUE TITLE
GLOBAL DAMAGE TAKEN

### ISSUE THREAD

**Issue by ravel1** [Blackhandpl/bugtracker#870]
Description: Damage is to high.
Warrior 93Lv NPC ID :82308
Shadowmoon Stalker melee hit 1358 physical
Shadowmoon Stalker Ferocious Bite hit 3014 physical
Shadowmoon Stalker melee hit 1756 physical
Shadowmoon Stalker melee hit 1725 physical
Shadowmoon Stalker melee hit 1974 physical
Shadowmoon Stalker Ferocious Bite hit 3585 physical
Shadowmoon Stalker melee hit 1741 physical
Shadowmoon Stalker melee hit 1674 physical
Shadowmoon Stalker melee hit 1432 physical
Shadowmoon Stalker melee hit 1562 physical
Shadowmoon Stalker melee hit 1583 physical
Shadowmoon Stalker melee hit 1601 physical

Warrior 93Lv NPC ID :46382
NPC all the time is missing.

**Comment by cheester93** [comment]
Moonstalker Sire  17 lv id 2237
melee hit Moonstalker sire 22 Physical     Moonstalker sire melee hit you 26 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 32 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 29 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 62 physical (critical)
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 28 physical 
melee hit Moonstalker sire 22 Physical     Moonstalker sire melee hit you 29 physical 
melee hit Moonstalker sire 22 Physical     Moonstalker sire melee hit you 28 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 23 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 23 physical 
melee hit Moonstalker sire 21 Physical     Moonstalker sire melee hit you 32 physical

**Comment by cheester93** [comment]
Moonstalker Sire 18 lv ID 2237
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 26 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 26 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 27 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 32 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 25 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 29 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 30 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 26 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 31 physical
melee hit Moonstalker sire 21 Physical Moonstalker sire melee hit you 51 physical (Critical)

**Comment by cheester93** [comment]
Moonstalker Matriarch 19 lv ID 2071 vs Hunter Survival 20 lv(Worgen)
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 32 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 39 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 41 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 34 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 41 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 33 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 38 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 30 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 35 physical
melee hit Moonstalker Matriarch 21 Physical    Moonstalker Matriarch melee hit you 85 physical (Critical)

**Comment by cheester93** [comment]
Encrusted Tide Crawler lv 20 ID  2233 vs Hunter Survival 20lv (Worgen)
Encrusted Tide Crawler melee hit 45 physical
Encrusted Tide Crawler melee hit 97 physical (Critical)
Encrusted Tide Crawler melee hit 54 physical
Encrusted Tide Crawler melee hit 67 physical
Encrusted Tide Crawler melee hit 46 physical
Encrusted Tide Crawler Rend damaged you 6 physical
Encrusted Tide Crawler melee hit 64 physical
Encrusted Tide Crawler Rend damaged you 7 physical
Encrusted Tide Crawler melee hit 62 physical
Encrusted Tide Crawler melee hit 45 physical

**Comment by cheester93** [comment]
Thistlefur Warrior lv 21 ID 33390 vs Hunter Survival 20lv (Worgen)
Thistlefur Warrior melee hit 53 physical
Thistlefur Warrior melee hit 113 physical (Critical)
Thistlefur Warrior Bloody Strike hit 69 physical
Thistlefur Warrior melee hit 70 physical
Thistlefur Warrior Bloody Strike hit 55 physical
Thistlefur Warrior melee hit 66 physical
Thistlefur Warrior melee hit 65 physical
Thistlefur Warrior melee hit 150 physical (Critical)
Thistlefur Warrior Bloody Strike hit 84 physical
Thistlefur Warrior melee hit 78 physical

**Comment by cheester93** [comment]
Thistlefur Shaman lv 22 ID 3924 vs Hunter Survival 20lv (Worgen)
Thistlefur Shaman Melee hit 69 Physical
Thistlefur Shaman Melee hit 63 Physical
Thistlefur Shaman Melee hit 55 Physical
Thistlefur Shaman Melee hit 153 Physical (Critical)
Thistlefur Shaman Melee hit 68 Physical
Thistlefur Shaman Melee hit 75 Physical
Thistlefur Shaman Melee hit 78 Physical
Thistlefur Shaman Melee hit 59 Physical
Thistlefur Shaman Melee hit 73 Physical
Thistlefur Shaman Melee hit 64 Physical

**Comment by cheester93** [comment]
Foulweald Totemic lv 23 ID 3750 vs Hunter Survival 20lv (Worgen)
Foulweald Totemic melee hit 83 Physical
Foulweald Totemic melee hit 68 Physical
Foulweald Totemic melee hit 63 Physical
Foulweald Totemic melee hit 89 Physical
Foulweald Totemic melee hit 71 Physical
Foulweald Totemic melee hit 63 Physical
Foulweald Totemic melee hit 124 Physical (Crushing)
Foulweald Totemic melee hit 73 Physical
Foulweald Totemic melee hit 80 Physical
Foulweald Totemic melee hit 76 Physical

**Comment by ravel1** [comment]
Probably works perfectly fine, but need confirmation.

**Comment by Gieniek** [comment]
Instancja: Prisoner of War. Dostałem 2 hity jeden za 20k drugi za 16k. Priest lvl 90 hp 34k
