### ISSUE TITLE
Warrior Spell  "Heroic Leap"

### ISSUE THREAD

**Issue by DjRai09** [Blackhandpl/bugtracker#885]
ID:71961

-Po nacisniecu spela wybieramy miejsce lądowania, klikamy  i nic się nie dzieje.

-Po naciśnięciu spell  wybieramy miejsce lądowania warriora klitamy, warrior wzbija się w powietrze i laduje w wybrane miejsce stunujac wszystkich na 2s i zadając 372 phisical damage w promieniu 8 jardów.

z tego co zauważyłem to  opis spella w grze jest trochę inny niż na wowhedzie  nie wiem  jak jest na globalu, i nie mam możliwości sprawdzenia.

http://www.wowhead.com/spell=71961/heroic-leap

**Comment by thomas33** [comment]
#254
