### ISSUE TITLE
Warrior Spell "Shockwave"

### ISSUE THREAD

**Issue by DjRai09** [Blackhandpl/bugtracker#886]
ID:87759

- Po naciśnieciu spella warrior stunuje wszystko przed saba i  samego siebie .

- Po naciśnięciu spella warrior stunuje  tylko wszystko przed sobą .

http://www.wowhead.com/spell=87759/shockwave

**Comment by thomas33** [comment]
#259

**Comment by siemo** [comment]
chyba nigdy tego nienaprawia:(
