### ISSUE TITLE
NPC: Brak dropu kraina Mount Hyjal

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#911]
Te mobki nie maja dropu:
1.Twilight Hunter, 39437
 http://www.wowhead.com/npc=39437/twilight-hunter
2.Twilight Proveditor, 39436
http://www.wowhead.com/npc=39436/twilight-proveditor
3.Twilight Slavedriver, 39438
http://www.wowhead.com/npc=39438/twilight-slavedriver
4.Hyjal Stag, 39588
http://www.wowhead.com/npc=39588/hyjal-stag
5.Lycanthoth Vandal, 39445
http://www.wowhead.com/npc=39445/lycanthoth-vandal
6.Hovel Brute, 39642
http://www.wowhead.com/npc=39642/hovel-brute
7. Hovel Shadowcaster, 39643
http://www.wowhead.com/npc=39643/hovel-shadowcaster
8. Howling Rifttdweller, 39844
http://www.wowhead.com/npc=39844/howling-riftdweller
9. Raging Firestorm, 39939
http://www.wowhead.com/npc=39939/raging-firestorm
10.Twilight Inferno Lord, 39974
http://www.wowhead.com/npc=39974/twilight-inferno-lord
11. Charbringer, 40336
http://www.wowhead.com/npc=40336/charbringer
12. Fierz Tormentor, Brak informacji na wowhead. Demon lvl 80 jest w miejscu "The Flamewake"
13.Lava Surger, 46911
http://www.wowhead.com/npc=46911/lava-surger
14.Core Hound, 46910
http://www.wowhead.com/npc=46910/core-hound
15. Twilight Scorchlord, 41500
http://www.wowhead.com/npc=41500/twilight-scorchlord
16. Twilight Field Captain, 41502
http://www.wowhead.com/npc=41502/twilight-field-captain
17.Scalding Rock Elemental, 40229
http://www.wowhead.com/npc=40229/scalding-rock-elemental
18.Twilight Vanquisher, 38913
http://www.wowhead.com/npc=38913/twilight-vanquisher
19. Twilight Flamecaller, 38926
http://www.wowhead.com/npc=38926/twilight-flamecaller
20. Twilight Overseer, 40123
http://www.wowhead.com/npc=40123/twilight-overseer

**Comment by ravel1** [comment]
#877
