### ISSUE TITLE
Monk

### ISSUE THREAD

**Issue by Mendalista** [Blackhandpl/bugtracker#944]
Description: Znikająca Energia
Current behaviour: Raz znika całościowo bez żadnych widocznych dot czy innego typu wysysaczy Energi.
Expected behaviour: Raz naładowana utrzymuję się do zurzycia.
Steps to reproduce the problem: wystarczy chwilę porzucać skille i zacznie się bugować.
Wowhead link:

**Comment by Sza65** [comment]
vide druid fereal

**Comment by thomas33** [comment]
#734
