### ISSUE TITLE
Potiony i jedzenie

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#957]
1. Jedzenie które wypada z mobków lvl NPC 40-70i potiony nie działają na każdym lvl. Potiony nie przywracaja hp ani many. Jedzenie podczas jedzenia nie przywraca hp nie wiem jak z mana.

**Comment by ravel1** [comment]
Sprawdziłem na kilkunastu potach i jedzeniu i wszystko działa jak trzeba.
