### ISSUE TITLE
Too Big For His Britches, Kill-Collect, Grubby Little Paws, A Mighty Hunger, A New Era for the Plaguelands, Gahrron's Withering Cauldron 

### ISSUE THREAD

**Issue by Fazo86** [Blackhandpl/bugtracker#959]
1. Too Big For His Britches, Kill-Collect, Grubby Little Paws, A Mighty Hunger, A New Era for the Plaguelands, Gahrron's Withering Cauldron 
2. 26823, 26595, 26605, 27167, 26999, 27053
3. Nie można podnieść q itemów
4. http://www.wowhead.com/quest=26823/too-big-for-his-britches
    http://www.wowhead.com/quest=26595/kill-collect
    http://www.wowhead.com/quest=26605/grubby-little-paws
    http://www.wowhead.com/quest=27167/a-mighty-hunger
    http://www.wowhead.com/quest=26999/a-new-era-for-the-plaguelands
    http://www.wowhead.com/quest=27053/gahrrons-withering-cauldron

**Comment by ravel1** [comment]
Dlaczego nie można podnieść tych itemów? Jaki jest konkretny powód?

**Comment by cheester93** [comment]
arleady looted

**Comment by ravel1** [comment]
#983
