### ISSUE TITLE
Questy: Trinkety, pierscienie, potiony

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#960]
1. Wszystkie questy gdzie mozna otrzymac trinkety, pierscienie potiony nie da sie ich odebrac. Działa tak w całej krainie northend. Sprawdzone na wielu qestach. Quest działa wysztjo jest wporzadku az do odebrania zakonczonego. Przykłady:
1. [Eyes Above]
http://www.wowhead.com/quest=12453/eyes-above
2, [The Thane of Voldrune]
http://www.wowhead.com/quest=12259/the-thane-of-voldrune

**Comment by ravel1** [comment]
Naprawione, ale na przyszłośc:
http://blackhand.pl/panel/fixes.php
