### ISSUE TITLE
Quest items + drop Draenor

### ISSUE THREAD

**Issue by Gieniek** [Blackhandpl/bugtracker#961]
1. W całym Draenor jest brak loota w NPC. 
2. Quest itemy nie działają/nie wypadaja z NPC w całym Draenor. Przykłady:
a) [Honor Has Its Rewards]
http://www.wowhead.com/search?&q=%20%5BLurkers%5D
b) [At the End of Your Rope]
http://www.wowhead.com/quest=34070/at-the-end-of-your-rope
c) [Shivertail's Den]
http://www.wowhead.com/quest=33929/shivertails-den

3. 95% NPC ma czaszki i nie można ich zabić. Przykłady:
a)Adherent Wing-Guard
http://www.wowhead.com/npc=75283/adherent-wing-guard
b)Adherent Squallbringer
http://www.wowhead.com/npc=75290/adherent-squallbringer

**Comment by ravel1** [comment]
Drop added, #983
