### ISSUE TITLE
Tarlna the Ageless MOB

### ISSUE THREAD

**Issue by cheester93** [Blackhandpl/bugtracker#997]
1. Tarlna the Ageless
2. 81535
3. jest to boss draenoru lvl jest ok ale jego dmg jak u mobka z 90-92 lv nie uzywa swoich skilli oraz jest ich kilka w jednym nakladaja sie (brak dropu)
4. http://www.wowhead.com/npc=81535/tarlna-the-ageless

**Comment by ravel1** [comment]
Sprawdz czy teraz jest ok, we wszystkich bosach zostala wprowadzona zmiana DMG.
